### ISSUE TITLE
HotReload doesn't work for DataTemplate property changes in custom controls

### ISSUE THREAD

**Issue by the8thC** [dotnet/maui#10066]
### Description

Hello! I've made a simple custom control that has a DataTemplate property. When the template is loaded (Grid, for example), I assign an event handler for PropertyChanged. I also assign the same handler to the Grid in DataTemplate used in ListView.

If I change a DataTemplate property in XAML for my control nothing happens, but for ListView -- the PropertyChanged event is fired. Also, for the custom control event is fired when the property is changed in code behind.

I've attached a video and a link to reproduction project repository.

https://user-images.githubusercontent.com/21204523/189682195-360ad54c-5165-4cf6-bd2a-481ff7c5299e.mp4

**P.S.** I'm one of the [DevExpress .NET MAUI controls](https://www.devexpress.com/maui/) developers, this issue has a normal priority for us and we do not have a workaround. Thank you for your help.

### Steps to Reproduce

1. Clone reproduction project repo
2. Build and run
3. While running, in XAML, try to change BackgroundColor property of the Grid in the DataTemplate in the custom control.

### Link to public reproduction project repository

https://github.com/the8thC/CustomControlHotReload

### Version with bug

6.0.400

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by drasticactions** [comment]
@the8thC This issue is caused by ListView not being supported for MAUI Xaml Hot Reload. There is already an issue for that (https://github.com/dotnet/maui/issues/9640) and I am working on figuring out how to make it work. If you can replicate your issue outside of ListView, please post a repo and I'm more than happy to look at it.

**Comment by drasticactions** [comment]
Actually, I reread the issue. Unless you have a custom ListView control then I don't know how that works for you, because it shouldn't. 

In terms of the custom controls, that issue should be fixed with https://github.com/dotnet/maui/pull/8947. TL;DR is MAUI was sending the wrong source info for nested controls, linking to the original XAML page rather than its implementation. That meant you could only implement changes inside of the original control XAML page. My change fixed that, and testing your repo it works fine.

I would test this against MAUI Main, or until whenever the next service release is that includes this PR.

**Comment by enisn** [comment]
How did you implement ItemTemplate in your control?

**Comment by the8thC** [comment]
> How did you implement ItemTemplate in your control?

https://github.com/the8thC/CustomControlHotReload
You can see here in this repo (which is in the 1st comment)

**Comment by the8thC** [comment]
@drasticactions I can still reproduce this on 6.0.540

https://user-images.githubusercontent.com/21204523/191705944-55cfc055-9ef2-4620-b6ef-de95a2dc5c3b.mp4

**Comment by drasticactions** [comment]
Did you try MAUI main?

In the Live Visual Tree for the control, if you click on the XAML Source Icon for a given item, does it go to the MainPage.xaml, or to the original controls XAML? If it goes to that, then it didn't work. If it does, then that's my fix, and you're having another bug.

**Comment by the8thC** [comment]
It goes to the original controls XAML. So that means it's some other bug?

https://user-images.githubusercontent.com/21204523/192253110-2e3f9098-f70c-4648-90b2-dc43f2be2dc9.mp4

**Comment by the8thC** [comment]
@drasticactions any updates on this?

**Comment by taublast** [comment]
The main step here would be to issue a doc on how to write custom controls compatible with hotrealod. Need guidelines for developers here along with *public* methods to trigger hot reload.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio 17.7.0 Preview 1.0. Can repro on android platform with above project.
[CustomControlHotReload-master.zip](https://github.com/dotnet/maui/files/11570822/CustomControlHotReload-master.zip)
![Android](https://github.com/dotnet/maui/assets/77434865/2476b8b4-52e5-4395-b378-152bde39475c)
