### ISSUE TITLE
Shadow.Radius on Android13 [API 33] is broken

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#10401]
### Description

	<Shadow Opacity="1"
			Offset="10,10"
			Radius="50"
			Brush="Red"></Shadow>

on an Image and Label following: API 31 left / API 33 right

![image](https://user-images.githubusercontent.com/46286656/193116528-e0c5e332-ed51-48f9-9001-a311c95983fa.png)

### Steps to Reproduce

add shadow to XAML element

### Link to public reproduction project repository

n/a

### Version with bug

6.0.486 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 13

**Comment by jsuarezruiz** [comment]
https://issuetracker.google.com/issues/244121207

**Comment by jsuarezruiz** [comment]
https://issuetracker.google.com/issues/238769745

**Comment by jsuarezruiz** [comment]
The TP1A.220905 build fixed that problem.

**Comment by Mous625** [comment]
Hi @jsuarezruiz, any news regarding this issue? Unfortunately, it is quite detrimental to my (and I'm sure many others) apps' design which was scheduled to be released for production this month.

**Comment by Stedy59** [comment]
I checked against the new API 31 build and all was good. When will MS push out this new emulator build?

**Comment by Mous625** [comment]
@Stedy59 as far as I know the issue is only present in Android 13 - API 33

**Comment by Stedy59** [comment]
Switch your Android SDK Manager to the Google feed and update your API 33 emulator build to v7.
That version includes the Android OS fix.

**Comment by Mous625** [comment]
@Stedy59 Indeed it fixes the issue. Great!

**Comment by Mous625** [comment]
Any news on when this issue will be fixed? The issue still occurs on physical devices such as the Samsung galaxy ultra s22 with the latest updates.

**Comment by South2AK** [comment]
Is there any news on this?

**Comment by LxyFlorian** [comment]
Looking for news too. The issue still occurs on physical device such as the Galaxy A13 with Android 13 - API 33

**Comment by Stedy59** [comment]
As @jsuarezruiz pointed out, the issue was from a bug in Android 13. Shortly after they fixed the bug, I updated my emulator and personal devices to the new Android build, and all worked properly.

As this was clearly an Android build issue, as @jsuarezruiz pointed out, this should be closed.

**Comment by South2AK** [comment]
@Stedy59 unfortunately I´m still getting the problem.

Visual Studio 17.7.0 Preview 3
**net8.0-android**

`          <Image
              Source="dotnet_bot.png"
              SemanticProperties.Description="Cute dot net bot waving hi to you!"
              HeightRequest="200"
              HorizontalOptions="Center" >



              <Image.Shadow>
                  <Shadow Brush="black" Radius="20" Offset="20,20"/>
              </Image.Shadow>
          </Image>`

This results in:
![image](https://github.com/dotnet/maui/assets/48831239/8091e61e-6011-42a1-aca6-abb948fd27fe)

**Comment by GlacierFox** [comment]
I'm getting this problem on my physical Samsung S21 with the latest update. Does this mean anyone using this type of device will have these terrible un-blurred shadows?

**Comment by GlacierFox** [comment]
Copied over the details from my previous post as this issue seems to have been reopened.

Here's a simple repro project I created to showcase the shadow problem:
[https://github.com/GlacierFox/MauiShadowError](https://github.com/GlacierFox/MauiShadowError)

I've just ran it on my physical Samsung Galaxy S21 and also my Samsung Galaxy Tab A7 Lite and I'm getting the same shadow errors. They both look to be on the same build number as mentioned above. This is what it looks like:

<img src="https://github.com/dotnet/maui/assets/9074086/ecbb35d9-7b41-4798-9680-7acbfe900482" width="400">

I then ran the exact same project in my API 33 - Android 13 Emulator and it looks fine as you can see below. I've also included an image of the current emulator device details:

| | |
|:-:|:-:|
| <img src="https://github.com/dotnet/maui/assets/9074086/4cfcb9b1-780b-4202-994b-a8f60dc71b34" width="400" /> | <img src="https://github.com/dotnet/maui/assets/9074086/d1924cf6-ad78-4c1f-800a-64b965bfb0e3" width="470" />|

I haven't been able to find a work-around for this problem and the shadows look terrible on my physical devices.

I've also just tested the app on a Samsung Galaxy S23 and everything looks fine so it seems it's a problem with the current most recent build of android available for Samsung S21, Galaxy Tab A7/A8 and possibly S22 devices.

**Comment by South2AK** [comment]
Is there any news on this?

**Comment by GlacierFox** [comment]
> Is there any news on this?

Not that I'm aware off. Still having this problem on both my phone and tablet. Not sure how this hasn't been sorted out yet, it's a major issue.

**Comment by jonmdev** [comment]
Holy shit. This was reported ONE YEAR AGO? I found this bug last week and fixed it within 1 hour:

https://github.com/dotnet/maui/issues/17886

I am not bragging by saying that. I had just already been inside similar systems of MAUI in the few days prior to understand what was happening for other reasons right before coming across it. So it was obvious to me. But it should have been equally obvious to any Microsoft employee.

You can apply the same solution I discuss in that thread through a Behavior or some other function for scaling the radius and offset parameters in Android until they decide to apply it. If anyone is not sure or has trouble, please post back and I can let you know some more, but only in C# (I don't use xaml).

But man, it just goes to what I was saying here:
https://github.com/dotnet/maui/discussions/17917

MAUI needs help. ☹️

Something like this should have been an easy fix for them. They use the same scaling function all over the internal Android code. Why on earth would something this simple be sitting for a year unsolved?

For example, you can see the opposite Android scaling function `FromPixels()` here: https://github.com/dotnet/maui/blob/main/src/Core/src/WindowOverlay/WindowOverlay.Android.cs

Is there anyone at Microsoft working on MAUI at all? :☹️

**Comment by jsuarezruiz** [comment]
> Holy shit. This was first reported **OVER ONE YEAR AGO**? I found this bug last week and fixed it within 1 hour:
> 
> #17886
> 
> Perhaps I got lucky as I had just already been inside similar systems of MAUI in the few days prior to understand what was happening for other reasons right before coming across it. So it was obvious to me. But it should have been equally obvious to any Microsoft employee.
> 
> All Android scaling to MAUI and back takes place through the `FromPixels` and `ToPixels` functions. These are used all over the MAUI Android code. Anyone at Microsoft who wrote any of the MAUI code should know that. So why this was left over a year unfixed is hard to understand.
> 
> You can apply the same solution I discuss in that thread through a Behavior or some other function for scaling the radius and offset parameters in Android until they decide to apply it. If anyone is not sure or has trouble, please post back and I can let you know some more, but only in C# (I don't use xaml).
> 
> But man, it just goes to what I was saying here: #17917
> 
> MAUI needs help. ☹️
> 
> Something like this should have been an easy fix for them. They use the same scaling function all over the internal Android code. Why on earth would something this simple be sitting for a year unsolved?
> 
> For example, you can see the opposite Android scaling function `FromPixels()` here: https://github.com/dotnet/maui/blob/main/src/Core/src/WindowOverlay/WindowOverlay.Android.cs
> 
> How could you write that code and not know what `ToPixels` and `FromPixels` do?
> 
> I am suspecting the people who actually wrote MAUI are long gone.
> 
> What is going on with MAUI at Microsoft? ☹️

The shadow offset size (scale) is not equal to the radius (the amount of blurring around the edges). Are different issues. This specific issue is related to a bug in Android https://issuetracker.google.com/issues/238769745?pli=1 (BlurMaskFilter is not blurring bitmaps) fixed by Google in the TP1A.220905 build. That is, this issue only occurs in Android 13 with a specific build, neither in previous versions nor in later versions after the fix.

The issues in the repo are prioritized based on different criteria:
- The impact.  Labels that indicate a high impact (For example, regression, or layout-grid since the use in almost any app is high). Feedback received, number of comments on the issue, etc.
- Etc.

Unfortunately, there are other issues with a higher score and for that reason this issue is still open. The fix would require changes to the shadow implementation on Android, it is not something trivial, require changes and testing in several devices and versions. I'm going to talk to the team about this specific issue to see if we can increase its priority.

**Comment by jonmdev** [comment]
> > Holy shit. This was first reported **OVER ONE YEAR AGO**? I found this bug last week and fixed it within 1 hour:
> > #17886
> > Perhaps I got lucky as I had just already been inside similar systems of MAUI in the few days prior to understand what was happening for other reasons right before coming across it. So it was obvious to me. But it should have been equally obvious to any Microsoft employee.
> > All Android scaling to MAUI and back takes place through the `FromPixels` and `ToPixels` functions. These are used all over the MAUI Android code. Anyone at Microsoft who wrote any of the MAUI code should know that. So why this was left over a year unfixed is hard to understand.
> > You can apply the same solution I discuss in that thread through a Behavior or some other function for scaling the radius and offset parameters in Android until they decide to apply it. If anyone is not sure or has trouble, please post back and I can let you know some more, but only in C# (I don't use xaml).
> > But man, it just goes to what I was saying here: #17917
> > MAUI needs help. ☹️
> > Something like this should have been an easy fix for them. They use the same scaling function all over the internal Android code. Why on earth would something this simple be sitting for a year unsolved?
> > For example, you can see the opposite Android scaling function `FromPixels()` here: https://github.com/dotnet/maui/blob/main/src/Core/src/WindowOverlay/WindowOverlay.Android.cs
> > How could you write that code and not know what `ToPixels` and `FromPixels` do?
> > I am suspecting the people who actually wrote MAUI are long gone.
> > What is going on with MAUI at Microsoft? ☹️
> 
> The shadow offset size (scale) is not equal to the radius (the amount of blurring around the edges). Are different issues. This specific issue is related to a bug in Android https://issuetracker.google.com/issues/238769745?pli=1 (BlurMaskFilter is not blurring bitmaps) fixed by Google in the TP1A.220905 build. That is, this issue only occurs in Android 13 with a specific build, neither in previous versions nor in later versions after the fix.
> 
> The issues in the repo are prioritized based on different criteria:
> 
>     * The impact.  Labels that indicate a high impact (For example, regression, or layout-grid since the use in almost any app is high). Feedback received, number of comments on the issue, etc.
> 
>     * Etc.
> 
> 
> Unfortunately, there are other issues with a higher score and for that reason this issue is still open. The fix would require changes to the shadow implementation on Android, it is not something trivial, require changes and testing in several devices and versions. I'm going to talk to the team about this specific issue to see if we can increase its priority.

Sorry @jsuarezruiz - I misunderstood.

If that is the case, it is obviously up to you how you manage your product, but if it was me personally, from what you said, specific to the issue in this thread (which is NOT then the same issue I posted about):

If something is a Google/Apple/Windows bug and that OS has fixed the bug on their end I don't think it should be your responsibility to write a code-around for the issue.

It is obviously not your fault and not your issue and it is not our responsibility as developers either. It is up to the user to ensure their OS is up to date and has the basic fix from their provider (Google/Apple/Microsoft).

Of all the issues, I wouldn't waste time coding a workaround for an underlying Android bug that has already been fixed years ago.

If it was me, I would just write a note telling people that and close the issue.

I suspect maybe there are a lot of "open" issues here that could be closed on similar grounds (issue fixed or not relevant for MAUI) and maybe closing more would make it easier to see what the actual existing issue backlog is or prioritize more.

While I have your attention, I see you have moved most of the issues I reported and listed here: https://github.com/dotnet/maui/discussions/17917 to backlog. 

The most critical one is the Editor iOS dysfunction reported here: https://github.com/dotnet/maui/issues/17757

Without this working no one can develop anything with user text input beyond 1-2 words for iOS. Do you have any thoughts on the probability of a fix or timeline?

All of these however will reduce any possibility of releasing any basic working app. Any thoughts on the backlog in general? Do you also get the sense that most of these "open" issues are not truly open issues but rather just clutter? Or what are your thoughts?

I am just trying to gauge things for my own planning. Thanks and sorry about the wrong conclusion I drew.

**Comment by GlacierFox** [comment]
@jonmdev now hang on there. You've come in here and misconstrued an issue and now you're advising the development team to close a critical isssue without a full understanding of that one either (which I had reopened). 

While the issue is actually tied to the base android operating system, it's not just a simple case of keeping your operating system up to date. I mean, do you not think, some of us as seasoned developers had came to the conclusion it's more complex than that?

The issue is that Samsung has not compiled the Android build with the fix into their custom build for a range of high end, low end and fairly recent phones and tablets running Android API version 33 specifically. (Samsung S21,  Galaxy Tab A8, to name a few) So no, you can't just update the device and yes, this requires a work-around for MAUI to be fully functional on these devices. 

Thanks for your efforts so far in looking into the issue @jsuarezruiz.

**Comment by albyrock87** [comment]
#26789 will avoid shadow bitmaps if your `Border` uses a solid background.

**Comment by bobby-asure** [comment]
Confirming this is still reproducing today on a recent .NET MAUI/.NET version, on a Samsung Android 13 device (API 33) — matches @GlacierFox's report above about the OEM build never picking up the Google `BlurMaskFilter` fix.

**Environment**
- Microsoft.Maui.Controls 10.0.100
- .NET SDK 10.0.400
- `net10.0-android`

**Repro**: a `Shadow` with a negative `Offset` (so it bleeds outside the casting view's own bounds, e.g. `Offset="0,-10"`) applied to a `Grid`, at low `Opacity` (~0.1). Expected a soft, gradually-fading darken of the adjacent content; actual result is a flat, hard-edged, uniformly-colored band with no visible blur regardless of `Radius`.

One data point that may help narrow down a workaround for affected OEM builds: per the discussion here and in #26789, switching the shadow-casting element from a `Grid`/`BoxView` to a `Border` with a solid (opaque, `StrokeThickness="0"`) background appears to take the Canvas-drawn "solid shape" shadow path rather than the bitmap/`BlurMaskFilter` path — worth calling out in the docs/workaround guidance for anyone hitting this on affected devices, since `Grid`/`BoxView` are easy to reach for and don't get that fast path.

Thanks for keeping this open and triaged — happy to provide more repro detail if useful.

**Comment by bobby-asure** [comment]
Follow-up: tested switching the shadow-casting element from a `Grid` to a `Border` with a solid, opaque, no-stroke background (per the discussion above and #26789) on the same affected Samsung Android 13 device. It did **not** resolve the issue — the shadow still renders as a flat, hard-edged band. Additionally, testing against a background that already has a light color tint nearby (not just plain white) made no visible difference either — the band looks equally solid/opaque either way, which suggests `Opacity` may not be respected at all on this device path, not just blur/`Radius`. Wanted to correct my earlier comment before it misleads anyone into thinking the `Border` workaround is reliable — for us it wasn't.
