### ISSUE TITLE
.NET MAUI Icon and Splash screen Looks Bad

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/maui#10669]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-MAUI-Icon-and-Splash-screen-Looks-B/10170967)._

---
.NET MAUI Icon and Splash screen looks bad and stretched even using latest VS 2022 17.4.0 Preview 3.0 with .NET 7 (Preview).

Below screenshot shows how the icon looks like for MAUI app (the one with RED round rectangle around it) while you can see how it should look like from the Xamarin app (the one with GREEN round rectangle around it):

![image](https://user-images.githubusercontent.com/1096616/195873817-51336abc-cddd-431b-83ea-dff4e55012c4.png)

Also see below how the icon looks poor and blurry on Windows while the Xamarin icon looks really good on Windows and also the "Color" attribute I set for icon was ignored for Windows since the icon shows magenta color behind the corners while the color I sat is "White":
![image](https://user-images.githubusercontent.com/1096616/195873869-367a0e1a-4496-4c24-8089-ff60e74160c2.png)
![image](https://user-images.githubusercontent.com/1096616/195873908-54fe0978-74a4-405b-9702-3021d89dfb30.png)

Now about splash screen, see how barcode splash screen looks like in the below screenshot on Android 12 while no splash screen is shows at all for Windows, it looks bad:
![image](https://user-images.githubusercontent.com/1096616/195873951-e76783ce-6348-43bb-b423-fafe2529357a.png)

Now I can workaround this last splash screen point on Android by using the appiconfg.svg as the splash screen but I don't know how it will look on iOS/macOS I haven't tried it yet but I believe on iOS the full splash screen should show there but still Xamarin used to work fine with the same splash screen I used for this test MAUI app.

I am attaching my test project for your reference along with the icon and splash screen I used.

---
#### Feedback Bot on 10/12/2022, 06:55 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by TamerIrdais** [comment]
@samhouts the screenshot images I provided on the original bug I reported are not showing in this link, can you please correct that?

**Comment by TamerIrdais** [comment]
I just tried this on iOS and noticed that the app icon looks very good but the splash screen does not, the splash screen is very small and doesn't fill the entire screen as it used to be on Xamarin, see below screenshot:

![MauiSplashScreen_iOS](https://user-images.githubusercontent.com/84446669/195779529-59d85809-a16a-4145-977e-96b5e03213ce.png)

Is the splash screen on .NET MAUI intended to show app icon in the middle of the screen and that's it?

**Comment by mattleibow** [comment]
Just linking to the docs: 
 - Splash screen: https://learn.microsoft.com/dotnet/maui/user-interface/images/splashscreen
 - App icon: https://learn.microsoft.com/dotnet/maui/user-interface/images/app-icons

Using the .NET MAUI splash screen generation is mainly just an image and a color:

```xml
<MauiSplashScreen Include="Resources\Splash\splashscreen.svg" Color="#512BD4" />
```

This forms the center icon and the background color. The reason for the "simple" design is that this is consistent on all platforms (and also no-one has really asked for any more complex layouts). 

In your image above, you just are missing the background color - and you don't need to add the screen padding around the icon. This is especially useful because you will need many images based on phone, tablet and even desktop app sizes. 

In the stretched image for Android, we fixed that in #5676 and should be out in the latest service releases. But the stretch will also go away if you make the splash image just be the plain transparent image and not have the blue background.

> We can have a look at custom layouts if there is an issue along with some expected result.

**Comment by TamerIrdais** [comment]
Thank you @mattleibow I understand the splash screen issue and how to fix it now but you said the icon stretch on android is fixed but is it already released or not? if not then when will it be released?

Also how about the poor icon quality on WinUI3?

**Comment by mattleibow** [comment]
This windows icons are fixed in #10515 and everything should be released in rc2. I will need to confirm but I think I also managed to get them backported into net6.

**Comment by TamerIrdais** [comment]
Thank you very much @mattleibow.

**Comment by mattleibow** [comment]
Closing this issue for now, please open a new issue with any other issues you find.

**Comment by TamerIrdais** [comment]
@mattleibow This icon issue is still active even on latest VS updates.
I tried it on both of the below VS2022 version using .NET 7.0:

Visual Studio 2022 Preview 17.5.0 Preview 1
Visual Studio 2022 17.4.0

You told me its going to be released with the next RC2.
