### ISSUE TITLE
[Android] Keyboard is not dismissed after tapping "Enter"

### ISSUE THREAD

**Issue by owl-guy** [dotnet/maui#10858]
### Description

When editing an Entry, the virtual keyboard is not dismissed after tapping the "Enter" button:
![maui_entry_bug](https://user-images.githubusercontent.com/114725843/197496795-9aac46db-4ff1-40d7-9eb6-7f55f1c3f205.gif)
This behaviour does not occur on iOS.

### Steps to Reproduce

1. Create a new .NET MAUI project
2. Add an entry
3. Tap into the entry control, type some text and tap "Enter"
4. The keyboard does not disappear, it remains visible until the back button is pressed

### Link to public reproduction project repository

https://github.com/owl-guy/EditorExample

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11 and up

**Comment by jsuarezruiz** [comment]
This issue will be fixed by https://github.com/dotnet/maui/pull/5740

**Comment by janseris** [comment]
@jsuarezruiz why are fixes in maui released 6 months after the actual fix is discovered?

**Comment by pulmuone** [comment]
> This issue will be fixed by #5740
In MAUI.iOS, it works the same as in Xamarin.Forms, but not in Maui.Android.

**Comment by owl-guy** [comment]
Still happens with latest stable version of .NET 7 (7.0.100)

**Comment by HopInTheCloud** [comment]
When will this be fixed?
This is a very basic function which is not working

**Comment by PureWeen** [comment]
Fixed by https://github.com/dotnet/maui/pull/11386

**Comment by pulmuone** [comment]
I am using Android Entry Keyboard bug fixed like this.
https://github.com/pulmuone/MauiAndroidKeyboard

**Comment by pulmuone** [comment]
> Still not fixed with the new update

I am using Android Entry Keyboard bug fixed like this.
https://github.com/pulmuone/MauiAndroidKeyboard

**Comment by HopInTheCloud** [comment]
> > Still not fixed with the new update
> 
> I am using Android Entry Keyboard bug fixed like this. https://github.com/pulmuone/MauiAndroidKeyboard

Thank you for this but I am just wondering why MAUI itself cannot be fixed and why updates are taking so long to be released. This issue goes way back and it is still not fixed

**Comment by iberosmen** [comment]
this still doesn't work in .net 7

**Comment by SaeedAtEposcompany** [comment]
Is this ever going to be fixed?

**Comment by stephenhauck** [comment]
Anyone .....
![image](https://user-images.githubusercontent.com/12648793/214730570-39843073-d63f-4e2e-b67c-4f93b18488bb.png)

**Comment by energywave** [comment]
I can confirm that with the latest version available today of MAUI .net 7 the Keyboard hide problem is still there on Android. :_(

**Comment by TamerIrdais** [comment]
@PureWeen This issue is till active on Android even with the latest net7.0 release, when this fix is going to be available/released?

**Comment by RsZoli** [comment]
@PureWeen This is a serious problem, why is this issue is closed?

**Comment by acaliaro** [comment]
testing on Android 10 Zebra device, it is still present

**Comment by DCox2016** [comment]
3/10/2023 issue still present

**Comment by Cruik** [comment]
I found a workaround here:
 https://stackoverflow.com/questions/72763590/can-you-minimize-the-soft-keyboard-on-android-from-text-completed-event
until the fix is released or if you are not able to update soon :)
