### ISSUE TITLE
[iOS] Startup Crash Specific to iOS 12 and .Net 7

### ISSUE THREAD

**Issue by jcsnider** [dotnet/maui#11525]
### Description

Default template MAUI app is crashing while on the startup splash screen on iPhones/iPads running iOS 12 when targeting .Net 7.

Works on .Net 6.

Works on .Net 7 when the device is running iOS 13+.

Crash occurs on both simulators and physical devices.

### Steps to Reproduce

1. Create a new .Net 7 MAUI project.
2. Try to run on a iOS 12.4 simulator or physical device.

### Link to public reproduction project repository

[https://github.com/jcsnider/Maui11525_ReproProject](https://github.com/jcsnider/Maui11525_ReproProject)

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

iOS

### Affected platform versions

iOS 12.4-12.5

### Did you find any workaround?

Not at this time.

### Relevant log output

```shell
Debug Log within Visual Studio (Not sure if relevant):

2022-11-21 08:30:05.855 MauiApp5[8120:408665] *** NSForwarding: warning: object 0x2809c4e70 of class 'Microsoft_Maui_Controls_Platform_iOS_CustomHoverGestureRecognizer' does not implement methodSignatureForSelector: -- trouble ahead
2022-11-21 08:30:05.855 MauiApp5[8120:408665] *** NSForwarding: warning: object 0x2809c4e70 of class 'Microsoft_Maui_Controls_Platform_iOS_CustomHoverGestureRecognizer' does not implement doesNotRecognizeSelector: -- abort

```

iOS Device Crash Log (Very consistent):
[ioscrashlog.txt](https://github.com/dotnet/maui/files/10057055/ioscrashlog.txt)
```
Incident Identifier: 0920B8C5-FE3A-4EE4-A7FF-0477762F59BF
CrashReporter Key:   730e27541ec32ccbcc1d375548cf97bc05896618
Hardware Model:      iPad4,1
Process:             BOOSTSecureUpload [8046]
Path:                /private/var/containers/Bundle/Application/7AC1EC21-B5C9-412B-AAD4-D015264F613D/BOOSTSecureUpload.app/BOOSTSecureUpload
Identifier:          [redacted]
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           [redacted] [517]


Date/Time:           2022-11-21 08:04:33.5432 -0500
Launch Time:         2022-11-21 08:04:21.5055 -0500
OS Version:          iPhone OS 12.5.5 (16H62)
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x00000001ba71b9ec
Termination Signal: Trace/BPT trap: 5
Termination Reason: Namespace SIGNAL, Code 0x5
Terminating Process: exc handler [8046]
Triggered by Thread:  0

Thread 0 name:  tid_303  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   CoreFoundation                	0x00000001ba71b9ec ___forwarding___ + 1444
1   CoreFoundation                	0x00000001ba71b9e8 ___forwarding___ + 1440
2   CoreFoundation                	0x00000001ba71d65c _CF_forwarding_prep_0 + 92
3   libobjc.A.dylib               	0x00000001b98ea3cc CALLING_SOME_+initialize_METHOD + 24
4   libobjc.A.dylib               	0x00000001b98efee0 initializeNonMetaClass + 296
5   libobjc.A.dylib               	0x00000001b98f1640 initializeAndMaybeRelock+ 34368 (objc_class*, objc_object*, mutex_tt<false>&, bool) + 260
6   libobjc.A.dylib               	0x00000001b98f95a4 lookUpImpOrForward + 244
7   libobjc.A.dylib               	0x00000001b9906858 _objc_msgSend_uncached + 56
8   BOOSTSecureUpload             	0x0000000100c7640c 0x100c2c000 + 304140
9   BOOSTSecureUpload             	0x0000000100c84468 0x100c2c000 + 361576
10  BOOSTSecureUpload             	0x0000000100f77d74 0x100c2c000 + 3456372
11  BOOSTSecureUpload             	0x0000000100f76b20 0x100c2c000 + 3451680
12  BOOSTSecureUpload             	0x0000000100f6c99c 0x100c2c000 + 3410332
13  BOOSTSecureUpload             	0x0000000100f6a668 0x100c2c000 + 3401320
14  BOOSTSecureUpload             	0x0000000100f3b670 0x100c2c000 + 3208816
15  BOOSTSecureUpload             	0x0000000100e8a5d0 0x100c2c000 + 2483664
16  BOOSTSecureUpload             	0x0000000100e8dc70 0x100c2c000 + 2497648
17  BOOSTSecureUpload             	0x0000000100fab2c4 0x100c2c000 + 3666628
18  BOOSTSecureUpload             	0x0000000101055a1c 0x100c2c000 + 4364828
19  UIKitCore                     	0x00000001e65c1224 -[UIViewController loadViewIfRequired] + 1012
20  UIKitCore                     	0x00000001e6531664 -[UINavigationController _updateScrollViewFromViewController:toViewController:] + 76
21  UIKitCore                     	0x00000001e653196c -[UINavigationController _startTransition:fromViewController:toViewController:] + 172
22  UIKitCore                     	0x00000001e65328a8 -[UINavigationController _startDeferredTransitionIfNeeded:] + 1112
23  UIKitCore                     	0x00000001e6533b3c -[UINavigationController __viewWillLayoutSubviews] + 164
24  UIKitCore                     	0x00000001e6516d4c -[UILayoutContainerView layoutSubviews] + 224
25  UIKitCore                     	0x00000001e7002170 -[UIView+ 13975920 (CALayerDelegate) layoutSublayersOfLayer:] + 1292
26  QuartzCore                    	0x00000001bec54c60 -[CALayer layoutSublayers] + 184
27  QuartzCore                    	0x00000001bec59c08 CA::Layer::layout_if_needed+ 1326088 (CA::Transaction*) + 332
28  QuartzCore                    	0x00000001bebbc3e4 CA::Context::commit_transaction+ 680932 (CA::Transaction*) + 348
29  QuartzCore                    	0x00000001bebea620 CA::Transaction::commit+ 869920 () + 640
30  UIKitCore                     	0x00000001e6b8385c __34-[UIApplication _firstCommitBlock]_block_invoke_2 + 124
31  CoreFoundation                	0x00000001ba6a7d6c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
32  CoreFoundation                	0x00000001ba6a7670 __CFRunLoopDoBlocks + 272
33  CoreFoundation                	0x00000001ba6a26d4 __CFRunLoopRun + 1024
34  CoreFoundation                	0x00000001ba6a1fb4 CFRunLoopRunSpecific + 436
35  GraphicsServices              	0x00000001bc8a479c GSEventRunModal + 104
36  UIKitCore                     	0x00000001e6b6ac38 UIApplicationMain + 212
37  BOOSTSecureUpload             	0x0000000100c585a4 0x100c2c000 + 181668
38  BOOSTSecureUpload             	0x0000000100f77e00 0x100c2c000 + 3456512
39  BOOSTSecureUpload             	0x0000000100f76b20 0x100c2c000 + 3451680
40  BOOSTSecureUpload             	0x0000000100f6c99c 0x100c2c000 + 3410332
41  BOOSTSecureUpload             	0x0000000100f6a668 0x100c2c000 + 3401320
42  BOOSTSecureUpload             	0x0000000100f3b670 0x100c2c000 + 3208816
43  BOOSTSecureUpload             	0x0000000100e8a5d0 0x100c2c000 + 2483664
44  BOOSTSecureUpload             	0x0000000100e90e78 0x100c2c000 + 2510456
45  BOOSTSecureUpload             	0x0000000100f4086c 0x100c2c000 + 3229804
46  BOOSTSecureUpload             	0x0000000100c83528 0x100c2c000 + 357672
47  BOOSTSecureUpload             	0x0000000100fa649c 0x100c2c000 + 3646620
48  libdyld.dylib                 	0x00000001ba1658e0 start + 4
```
```

**Comment by jcsnider** [comment]
[Repro case added.](https://github.com/jcsnider/Maui11525_ReproProject) To be clear it is the default maui shell application from the visual studio template.

**Comment by Raghavendra-Roy** [comment]
Thread started:  #2
Resolved pending breakpoint for 'Program.Main(System.String[])' to D:\Projects\ProjectName\Platforms\iOS\Program.cs:10 [0x00000].
Loaded assembly: data-0x109f7c000 [External]
Loaded assembly: data-0x109f90000 [External]
Resolved pending breakpoint at 'D:\Projects\ProjectName\Platforms\iOS\Program.cs:13,1' to void Program.Main (string[] args) [0x00001].
The app has been terminated.

**Comment by Raghavendra-Roy** [comment]
this is the above log when app launches and crashes almost immediately after updating to .net7.

Platforms details:
iOS- 15.6
Minimum OS version is 15.4

**Comment by dbullen-uk** [comment]
Apologies for my ignorance, does this mean the issue is now fixed? What would I need to do to take advantage of this, as it stops any Maui apps working in iOS < 13. Or do we have to wait for the next release? Is there a workaround in the meantime?

**Comment by jcsnider** [comment]
Current version of .Net 7 which is 7.0.49 was released 23 days ago so I'd imagine the next build with this fix will be out in a week or two. I am unaware of any preview/nightly automated builds that you could quickly take advantage of.

If your project will run on .Net 6 then you could always fall back to that temporarily as this crash only exists in .Net 7.

**Comment by dbullen-uk** [comment]
So the fix for this was apparently released yesterday (https://github.com/dotnet/maui/releases/tag/7.0.52)
I've upgraded everything, created a default maui shell application from the visual studio template, attempted to run on a local iPhone 6 (iOS 12.4.8) and still have the same problem (splash screen shows for a few seconds then app closes).
Has anyone else been able to get this working?

**Comment by jathanaselos** [comment]
Having the same problem.. so annoying to read this msftbot message.
Microsoft, make this a priority fix please!
