### ISSUE TITLE
Shell flyout background color does not change in .NET 7.0

### ISSUE THREAD

**Issue by Miro382** [dotnet/maui#12325]
### Description

Shell flyout background color does not change in .NET 7.0

This issue is the same as: [6552](https://github.com/dotnet/maui/issues/6552)
This issue has been fixed for .NET 6.0 by PR: [6901](https://github.com/dotnet/maui/pull/6901)

But this problem is still present in .NET 7.0. 

### Steps to Reproduce

Set in Shell FlyoutBackground.
Background of the flyout always uses the dark/light theme default.

### Link to public reproduction project repository

Don't have

### Version with bug

7.0 (current)

### Last version that worked well

6.0.424

### Affected platforms

Windows

### Affected platform versions

All Windows SDK

**Comment by vadimffe** [comment]
I can confirm that. While setting in App.xaml:

```
    <Shell FlyoutWidth="85" FlyoutBehavior="{OnIdiom Phone=Disabled, Default=Locked}" 
           FlyoutBackground="#111111">
```

While debugging background is changing, but if I stop debugging and start my app again FlyoutBackground is flushing shortly with my custom color, but then is getting a default value again which is black. I have also tried to set it in Styles.xaml, but it has no effect.

```
  <Style TargetType="Shell" ApplyToDerivedTypes="True">
    <Setter Property="Shell.BackgroundColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource Gray960}}" />
    <Setter Property="Shell.FlyoutBackground" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource Gray960}}" />
    <Setter Property="Shell.ForegroundColor" Value="{OnPlatform WinUI={StaticResource Primary}, Default={StaticResource White}}" />
    <Setter Property="Shell.TitleColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource White}}" />
    <Setter Property="Shell.DisabledColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray950}}" />
    <Setter Property="Shell.UnselectedColor" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray200}}" />
    <Setter Property="Shell.NavBarHasShadow" Value="False" />
    <Setter Property="Shell.TabBarBackgroundColor" Value="{AppThemeBinding Light={StaticResource White}, Dark={StaticResource Black}}" />
    <Setter Property="Shell.TabBarForegroundColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
    <Setter Property="Shell.TabBarTitleColor" Value="{AppThemeBinding Light={StaticResource Primary}, Dark={StaticResource White}}" />
    <Setter Property="Shell.TabBarUnselectedColor" Value="{AppThemeBinding Light={StaticResource Gray900}, Dark={StaticResource Gray200}}" />
  </Style>
``` 

Maybe there is something else, but searching for FlyoutBackground is not giving any other results, so I assume there are no other setting for FlyoutBackground in my test app.

Please, provide some fix.

**Comment by rneeft** [comment]
An other example: when upgrading [WeatherTwentyOne](https://github.com/dotnet/maui-samples/tree/main/6.0/Apps/WeatherTwentyOne) example to .net 7, the menu colour is also changed to white in Windows 11.

**Comment by acrigney** [comment]
This is an issue for me, would anyone be working on this soon?

**Comment by vadimffe** [comment]
Is there somebody working on this? It would be nice to get this fixed soon.

**Comment by Orgbrat** [comment]
Says above they have moved this to Backlog milestone which it should be fixed. Looks like they had it fixed in 6.0 and then broke it again in 7.0.

**Comment by acrigney** [comment]
Yes guys this is really ridiculous a small bug like this means that we can
not move to .net 7. I will be making a support request for this soon it's
just that when our admin changes we  have to reset our support plan now I
am waiting for our admins to fix it.

**Comment by jsuarezruiz** [comment]
Doing some test debugging the Maui Core (main branch, similar to latest 7.0 release), cannot reproduce the issue:
![image](https://user-images.githubusercontent.com/6755973/216558012-090bb3ed-33ae-44c2-bba7-7b3ebe372104.png)

Could someone attach a small sample where reproduce it?

**Comment by acrigney** [comment]
Guys I am about to go skiing for a month so hopefully someone else can test
this, are there any updates recently?

**Comment by Miro382** [comment]
I've tested the app and it's still happening.

![obrázok](https://user-images.githubusercontent.com/20913015/216667223-d4e23d94-6eb3-441c-8a45-a7b9cba0dc46.png)


Edition	Windows 11 Pro
Version	22H2
Installed on	‎18. ‎11. ‎2022
OS build	22621.1194
Experience 1000.22638.1000.0


I have installed all available windows updates.

**Comment by vadimffe** [comment]
@jsuarezruiz have you set background while debugging? In this case it works. However if you stop debugging and run your app again with defined background colour, background colour is not set. Also if you publish your app, background is not set. Please see my repo for issue reproduction, but I don't think it is much different from yours:
https://github.com/vadimffe/ShellFlyoutBackgroundIssue

![image](https://user-images.githubusercontent.com/72302395/216631762-26723424-eb39-42ef-aeba-83d8c76c2971.png)

**Comment by Miro382** [comment]
I'm attaching a video on OneDrive with the error. It happens to me during debug as well. But you can see some flash when it starts. That is, at the beginning it sets the color but then it overwrites.

[https://1drv.ms/v/s!AlEOf2Tm2MYS4yN3yvkF-romPp7x?e=VpaFlO](https://1drv.ms/v/s!AlEOf2Tm2MYS4yN3yvkF-romPp7x?e=VpaFlO)

Here is my test project: [https://github.com/Miro382/MAUIFlyoutIssue](https://github.com/Miro382/MAUIFlyoutIssue)

**Comment by jsuarezruiz** [comment]
> I'm attaching a video on OneDrive with the error. It happens to me during debug as well. But you can see some flash when it starts. That is, at the beginning it sets the color but then it overwrites.
> 
> https://1drv.ms/v/s!AlEOf2Tm2MYS4yN3yvkF-romPp7x?e=VpaFlO
> 
> Here is my test project: https://github.com/Miro382/MAUIFlyoutBug

Thanks for the test project. Have been able to reproduce the issue and will be fixed by https://github.com/dotnet/maui/pull/13132
