### ISSUE TITLE
[Bug] Derived control renders with the handler of the base class

### ISSUE THREAD

**Issue by vanka78bg** [dotnet/maui#1298]
### Description

Let's assume we have a base control `MyBaseView` with its corresponding handler `MyBaseViewHandler`. Now, let's create a derived control `MyDerivedView` with a new handler `MyDerivedViewHandler`. Both handlers are registered at startup with the following code:

```csharp
public class Startup : IStartup
{
    public void Configure(IAppHostBuilder appBuilder)
    {
        appBuilder
            .UseFormsCompatibility()
            .UseMauiApp<App>()
            .ConfigureMauiHandlers(handlers =>
            {
                handlers.AddHandler<IMyBaseView, MyBaseViewHandler>();
                handlers.AddHandler<IMyDerivedView, MyDerivedViewHandler>();
            });
    }
}
```

The problem is that the derived control `MyDerivedView` still uses the base handler `MyBaseViewHandler` at runtime, even though it has a new handler registered. The order the handlers are registered is not important.

### Steps to Reproduce

1. Start the attached sample application
2. Place breakpoints in the constructors of `MyBaseViewHandler` and `MyDerivedViewHandler`
3. Observe which breakpoint is being hit

### Expected Behavior

The expected behavior is that the derived control `MyDerivedView` would use the derived handler `MyDerivedViewHandler`.

### Actual Behavior

The actual behavior is that the derived control `MyDerivedView` still uses the base handler `MyBaseViewHandler`.

### Basic Information

Visual Studio: Visual Studio 2019 Version 16.11.0 Preview 1.0
.NET SDK: .NET 6.0 preview 4

### Reproduction Link

[MauiApp.zip](https://github.com/dotnet/maui/files/6647203/MauiApp.zip)

### Workaround

The workaround is to have a common base class without a handler and two derived classes with handlers. This approach works only if we have a full control over the class hierarchy. Inheriting form framework classes with handlers is not possible. For instance, inheriting from `Button` and providing a custom handler for the derived button won't work, because the base handler `ButtonHandler` would be picker always.

### Impact

The impact of this bug is that it practically makes it impossible to have derived controls with some customizations.

**Comment by vanka78bg** [comment]
Interestingly, after some testing I have found the bug is reproducible only if I register the handler via the interface.

For instance, if I register the handler like this (without interfaces):

```csharp
handlers.AddHandler<MyBaseView, MyBaseViewHandler>();
handlers.AddHandler<MyDerivedView, MyDerivedViewHandler>();
```

Now the handler is resolved correctly, i.e. `MyDerivedView` is rendered with `MyDerivedViewHandler`.

However, if I register the handler like this (with interfaces):

```csharp
handlers.AddHandler<IMyBaseView, MyBaseViewHandler>();
handlers.AddHandler<IMyDerivedView, MyDerivedViewHandler>();
```

In this case the handler is resolved incorrectly, i.e. `MyDerivedView` is rendered with `MyBaseViewHandler`.

Please, keep in mind that the `IMyDerivedView` interface inherits from the `IMyBaseView` interface and the `MyDerivedView` class inherits from the `MyBaseView` class. I do not know why using interfaces would cause such misbehavior.

**Comment by mattleibow** [comment]
This is exactly the issue we found and why we also switched to registering the concrete views.

I can't recall exactly the reason this happens, maybe @PureWeen knows. But there was some specific reason because of the way the lookup worked. That may have been an issue because of the ordering of the interfaces and the way the .NET system works when searching for interfaces.

**Comment by PureWeen** [comment]
I think this is a real bug with how the lookups here work

https://github.com/dotnet/maui/blob/53a1d32d9114893a4a92dec727e6a2e22b6305e2/src/Core/src/Hosting/Internal/MauiServiceProvider.cs#L117

**Comment by shimingsg** [comment]
verified repro with VS 17.2.0 Preview 3.0 [32308.470.main] on Android 11 Emulator

**Comment by EmilAlipiev** [comment]
but documentations is still not up to date? all handler things are mess in my opinion. When using the concrete registration, it always generates a new instance instead of reusing and updating my cross platform instance.
