### ISSUE TITLE
[Windows/WinUI] Main window doesn't have an accessible name by default

### ISSUE THREAD

**Issue by spadapet** [dotnet/maui#14465]
### Description

MAUI's main window on Windows desktop has no title by default and is therefore not accessible. When the MAUI window gets focus, the narrator will say "DesktopChildSiteBridge" which is not helpful. By default, the window title should be anything but empty, it could be the app name by default.

Is there an easy way in XAML to set the window title?

### Steps to Reproduce

**REPRO:**

1. In VS 2022, create a new MAUI app from template
2. Build and run the app on the Windows desktop
3. Turn on Windows narrator, set focus to the MAUI app

**EXPECT:**
Narrator announces the app name

**RESULT:**
Narrator announces that "DesktopChildSiteBridge" was activated

**NOTE:** If you F5 to build and run, you can use the in-app toolbar to run the accessibility checker from Visual Studio. There should be one error that an element doesn't have a name. It's referring to the main window not having a name.

![image](https://user-images.githubusercontent.com/2523431/230702998-eb721536-3feb-42c7-8291-20973ae62627.png)

### Link to public reproduction project repository

N/A, use default template

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net7.0-windows10.0.19041.0

### Did you find any workaround?

In App.xaml.cs, I can override the CreateWindow method to inject my own window title. This shouldn't be required.

**Comment by PureWeen** [comment]
@spadapet this is already fixed in NET 8 
https://github.com/dotnet/maui/pull/13521

The `DesktopChildSiteBridge` is a WinUI bug that'll hopefully be fixed in 1.3 https://github.com/dotnet/maui/issues/10131

I don't think there's really a bug here but I do think we need some additional APIs
An attached property for setting `Window` title would be useful. I think also including the `Window` as a class inside the templates would be useful.

**Comment by davidortinau** [comment]
I installed 17.5.4 with .NET MAUI 7.0.81. Adding a Title to AppShell.xaml works and displays. fwiw

**Comment by spadapet** [comment]
@PureWeen thanks, then this issue can probably be closed due to #13521. Discussion about whether a new attached property would be useful can happen elsewhere.

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. Repro on Windows 11 with below Project:
[14465.zip](https://github.com/dotnet/maui/files/11866457/14465.zip)(.NET 7)

**Comment by BurkusCat** [comment]
I think this is still broken outside of Shell. I've so far not found any way to set the title on a WinUI app (`package.appxmanifest`, `<ApplicationTitle>`, `WindowHandle = WinRT.Interop.WindowNative.GetWindowHandle(window); window.AppWindow.Title = "test"; window.Title = "test";` all don't work).

My expectation would be the default window title would be based on the value set for `ApplicationTitle`.
