### ISSUE TITLE
[Android] Button text alignment inconsistencies

### ISSUE THREAD

**Issue by rachelkang** [dotnet/maui#14712]
### Description

It is expectated that button content is centered unless otherwise specified.

On Android, however, this is not always the case. The button text here appears start-aligned on initialization. Only on an interaction like switching the screen orientation to horizontal (and back to vertical) do we see that the button text has been updated to be properly centered. As seen, this does not appear to be an issue with the button imageSource, but only the button text.

https://user-images.githubusercontent.com/21988533/233678784-4b9db048-d3f3-4c27-a348-c5607cecfc2b.mp4

### Steps to Reproduce

1. Pull down https://github.com/rachelkang/recipeSearch
2. Deploy app to physical Android device
3. Notice the button text is start-aligned
4. Flip phone to horizontal orientation
5. Notice the button text is now centered
6. Flip phone back to vertical orientation
7. Notice the button remains centered in vertical orientation now as well

### Link to public reproduction project repository

https://github.com/rachelkang/recipeSearch

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 12

**Comment by Aliaksandr-Tuzik** [comment]
Any updates on this one?
Would be much appreciated

**Comment by jsuarezruiz** [comment]
Could you try with the latest net8 version?. Cannot reproduce the issue on main branch:
![image](https://github.com/dotnet/maui/assets/6755973/e68c7d33-cadd-4d61-a478-5ed6fac80c18)

Used https://github.com/rachelkang/recipeSearch/blob/c97687487d70d6ecef329fe6f1c9b0c89b32fda8/WhatToEat/Views/StartingPage.xaml

**Comment by mmyers299** [comment]
I'm having this same issue. @jsuarezruiz it being fixed in Net8 doesn't help those of us with production issues. We can't put beta's in prod to fix UI bugs.

**Comment by GiuLive13** [comment]
For everyone who facing this issue:
There is a specific MauiVersion which is mostly the way to go in cases of unexpected behaviors (e.g. Calendar).
Add this to your .proj between a PropertyGroup:

`<MauiVersion>7.0.59</MauiVersion>`

In my case I put it in the PropertyGroup where the TargetFramework Tags are also listed.
For seeing the effect of the changes its helpful to delete the _bin_ and _obj_ folder in your local project and restart your IDE.
It´s not the best solution, but maybe a workaround until .NET8.0 releases.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Not repro on android platforms with sample project. (.NET 8)
https://github.com/rachelkang/recipeSearch

**Comment by andy-waxman** [comment]
I am still having this issue using version 8.0.6 of Microsoft.Maui.Controls and Microsoft.Maui.Controls.Compatibility

**Comment by samhouts** [comment]
@andy-waxman Would you be able to open a new issue and provide a reproduction sample? Thanks!
