### ISSUE TITLE
[ANDROID] Requesting Read-Write External Storage in .net 7 not working

### ISSUE THREAD

**Issue by tataelm** [dotnet/maui#14729]
### Description

"android.permission.READ_EXTERNAL_STORAGE" and "android.permission.WRITE_EXTERNAL_STORAGE" can't be requested. I have tried adding it under AndroidManifest.xml and adding it as assembly under MainActivity.cs but no use. 

Besides "ShouldShowRationale" not getting triggered, I can't change the permissions manually neither because there is none. 

### Steps to Reproduce

1. Create a brand new project with .net 7.
2. Add these under AndroidManifest.xml

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

3. Add a method on main page and trigger it via button click

```
 public async Task CheckForPermissions()
    {               
        var status_write = await Permissions.CheckStatusAsync<Permissions.StorageWrite>();
        var status_read = await Permissions.CheckStatusAsync<Permissions.StorageRead>();

        if (Permissions.ShouldShowRationale<Permissions.StorageWrite>())
        {
            // just testing
        }

        if (Permissions.ShouldShowRationale<Permissions.StorageRead>())
        {
            // just testing
        }

        status_write = await Permissions.RequestAsync<Permissions.StorageWrite>();
        status_read = await Permissions.RequestAsync<Permissions.StorageRead>();

        if (status_write != PermissionStatus.Granted)
        {
            // still not granted
        }

        // forward user to settings so they can grant permission
        AppInfo.Current.ShowSettingsUI();
    }
```

4. You will be forwarded to application settings and you won't find any permission requests.

### Link to public reproduction project repository

none

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android api 33

**Comment by moljac** [comment]
Can confirm. Under further investigation.

Repro sample:

[AppMAUI.Issue14729.PermissionsExternalStorage.zip](https://github.com/dotnet/maui/files/11309965/AppMAUI.Issue14729.PermissionsExternalStorage.zip)

**Comment by Laim** [comment]
Having the same issue, very annoying.  Was hoping to let users backup their database to wherever they wanted but seems to be near impossible to get working on .NET 7 against API 33 at the moment.

**Comment by mosabbir786** [comment]
> We've added this issue to our backlog, and we will work to address it as time and resources allow. If you have any additional information or questions about this issue, please leave a comment. For additional info about issue management, please read our [Triage Process](https://github.com/dotnet/maui/blob/main/docs/TriageProcess.md).
Is this issue resolved or not

**Comment by Kapusch** [comment]
Hi @tataelm , I know this may not be ideal for you, but I think this has been fixed in .NET 8.
Did you give it a try?

**Comment by tataelm** [comment]
Hi @Kapusch , I've solved that somewhat different. I totally forgot that I've opened a case on that. 

This was my solution;

    [RelayCommand]
    async Task ImportPlaylist()
    {
        await FilePicker.Default.PickAsync().ContinueWith(PlaylistFileImportAction);
    }
    
    private async Task PlaylistFileImportAction(Task<FileResult> task)
    {
        var result = await task;
        // rest of the logic
    }
    
    
This was the solution I came up with after struggling it with many hours.

**Comment by MattePozzy** [comment]
Android 14 .net 8
`PermissionStatus storageStatus = await Permissions.CheckStatusAsync<Permissions.StorageWrite>();`
return always false.
In manifest there is 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`.

**Comment by CallumHoughton** [comment]
This is still an issue - it returns denied for both StorageRead and StorageWrite on Android 14

**Comment by Fiontan** [comment]
This is an issue for us in a migration from Xamarin forms and is becoming a bit of a showstopper. We've followed all the recommendations for the manifest. Taking/uploading images and videos kind of works (we are also seeing a significantly awful degradation in performance for encrypted files but that's a different story although who knows if it's related or not), but as soon as a user tries to upload from "File manager" (and not pics/vids):
<img width="105" alt="image" src="https://github.com/dotnet/maui/assets/1700120/11859a19-bb6f-4d45-bf40-e1fcee291bbf">
