### ISSUE TITLE
Shell Flyout text missing in Release mode, when using DataTemplate without x:DataType

### ISSUE THREAD

**Issue by shadowfoxish** [dotnet/maui#14865]
### Description

When using Shell.ItemTemplate as discussed [here ](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/flyout?view=net-maui-7.0#define-flyoutitem-appearance) to customize the look of the FlyoutItems, the text and icon are not visible in RELEASE mode, but are visible in DEBUG mode. The _placeholders_ exist for the menu items, which leads me to think databinding differences between RELEASE and DEBUG?

If you remove the Shell.ItemTemplate, then the text/icons appear normally.

![image](https://user-images.githubusercontent.com/12143535/235523400-8e70754b-2a0a-4e91-8c9f-4b6877f1ecce.png)

![image](https://user-images.githubusercontent.com/12143535/235524211-c30ed04d-068a-4265-8cfa-58ca944f4010.png)

### Steps to Reproduce

Create a shell application, with a mixture of ShellContent and FlyoutItems. 
Override the default template for items as documented in the official documentation.
Run the project in RELEASE mode on an android device, and notice the text and icons for the menu options in the Flyout are not visible.
Run the project in DEBUG mode, and the text and icons are visible as expected.

View the sample app in the reproduction repository below. (This example was used for another issue, I just added the shell to it to demonstrate the bug in the May 1st commits)

### Link to public reproduction project repository

https://github.com/shadowfoxish/Temp-CollectionViewFormattedStringSlowness

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Tested on Android 9.0, API 28

### Did you find any workaround?

Not setting the custom template allows the text and icons to render as their default implementations.

**Comment by shadowfoxish** [comment]
I actually just noticed during testing of my release build, that a page I have a Carousel on, and it's also not showing in Release mode. It renders the top bar, but nothing else. Not picking on Carousel, but its the only exotic thing on this page, and no other page in my app uses it.

```xaml
<CarouselView x:Name="carousel" Loop="False" IndicatorView="indicatorView" VerticalOptions="FillAndExpand">
	<CarouselView.ItemsSource>
		<x:Array Type="{x:Type ContentView}">
			<controls:PickListView />
			<controls:ReturnPickedItemsView />
			<controls:MyPickTicketsView />
		</x:Array>
	</CarouselView.ItemsSource>
	<CarouselView.ItemTemplate>
		<DataTemplate>
			<ContentView Content="{Binding .}" VerticalOptions="FillAndExpand" />
		</DataTemplate>
	</CarouselView.ItemTemplate>
</CarouselView>
```

**Comment by shadowfoxish** [comment]
@PureWeen 
After a lot of reading and experimenting, I figured out whats happening in both of my cases (Flyout and the Carousel). In both cases, I was not explicitly specifying the `x:DataType attribute` in the `<DataTemplate>`s. 

I updated the Flyout one to `x:DataType="ShellContent"` and the Carousel one to `x:DataType="ContentView"` and both of them wonderfully started working properly.

I pushed the fix to the Repro repo.

I suppose the underlying issue remains, since there is a deviation between DEBUG and RELEASE, but at least there seems to be a good fix for it. Dont leave <DataTemplate>s without x:DataTypes.

**Comment by dgerding** [comment]
@shadowfoxish Thanks for the clear post. I'm having the same issue and will go try your fix. Will report back.

**Comment by dgerding** [comment]
Unfortunately, just adding the x:DataType to my Flyout DataTemplate didn't fix things. Will follow.

**Comment by dgerding** [comment]
No luck so far. Looking forward to next PR, thanks @PureWeen

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.7.0 Preview 2.0. This issue does not repro on Android 13.0-API33 with below Project in Debug and Release mode:
[CollectionViewFormattedStringSlowness.zip](https://github.com/dotnet/maui/files/11955747/CollectionViewFormattedStringSlowness.zip)

Release mode:
![image](https://github.com/dotnet/maui/assets/97647558/06b4b530-deaa-4a30-8b2f-539668f05c9d)

**Comment by DM-98** [comment]
I had similar issue on this. After many hours of testing, I found the bug. It happens when you apply x:DataType="local:AppShell" on it.. Which is unfortunate since I'd like compiled bindings on it for improved data binding performance...
