### ISSUE TITLE
Safe area insets CSS env not working on Android

### ISSUE THREAD

**Issue by jbonnett92** [dotnet/maui#14894]
### Description

Safe area insets work in CSS env on iOS but not Android

### Steps to Reproduce

Create CSS for safe area:
```css
    padding-top: env(safe-area-inset-top);
    padding-bottom: env(safe-area-inset-bottom);
    padding-right: env(safe-area-inset-right);
    padding-left: env(safe-area-inset-left);
```

### Link to public reproduction project repository

N/A

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Not sure but I have Android 12

### Did you find any workaround?

No workaround

### Relevant log output

```shell
No log
```

**Comment by Eilon** [comment]
Hi @jbonnett92 , can you show more info about how you're using this CSS in your app, and also a screenshot showing where the problem is? Ideally you could post a complete repro app to a public GitHub repo so that we can investigate.

**Comment by jbonnett92** [comment]
I'm sorry I don't have a public repo also a screenshot wouldn't show what the issue is, but I will attach a couple of photos:
![image](https://user-images.githubusercontent.com/3740700/235739073-5f662334-84f4-49fe-a196-0af932a6de4f.jpeg)
![image](https://user-images.githubusercontent.com/3740700/235739119-fc122715-9b3d-4022-b566-bbc23311318e.jpeg)

**Comment by jbonnett92** [comment]
I already said I can't provide a repo, and it is simple to replicate!

**Comment by Eilon** [comment]
@jbonnett92 I think we need more info in order to understand the issue. Are you using a WebView? Exactly what HTML is in the webview? Or is it a BlazorWebView? A custom control? Can you circle on the images where you think it is rendering incorrectly? Right now I just don't think we have enough information to go further. If it's simple to replicate, please provide as many details as possible.

**Comment by Eilon** [comment]
Ah, so you're saying that on iPhone it's fine, but on this Android device the text is too close to the notch?

![image](https://user-images.githubusercontent.com/202643/235781606-06e1c134-f919-4bb3-9468-90bdc870ccb3.png)

**Comment by jbonnett92** [comment]
Yes

**Comment by Eilon** [comment]
Gotcha. And to which selector/element are those CSS attributes applied? The CSS provided in the original post was incomplete.

**Comment by Eilon** [comment]
And also can you show an example of the HTML that is being shown?

**Comment by jbonnett92** [comment]
In this case it is just the header, the HTML doesn't matter. But I will post a page in a min to show you what I mean.

**Comment by jbonnett92** [comment]
Actually I will just give a rundown of code:
```csharp
<body>
</body>
```

```css
html {
    background: #f00;
}

body {
    background: #fff;
    padding-top: env(safe-area-inset-top);
    padding-bottom: env(safe-area-inset-bottom);
    padding-right: env(safe-area-inset-right);
    padding-left: env(safe-area-inset-left);
}
```

This should give you something looking like this, except for the border is red rather than blue with the center of the page just being white rather than the site itself:
![image](https://user-images.githubusercontent.com/3740700/235783641-d916704b-2273-4ac0-97fd-c81baf2f0b5d.png)

**Comment by Eilon** [comment]
Alright this looks like it should be enough to continue, thank you!

**Comment by jbonnett92** [comment]
Awesome, thank you

**Comment by jbonnett92** [comment]
By the way I don't mind if the anwser is a workaround

**Comment by jbonnett92** [comment]
Unfortunetly that will break my design.

**Comment by jbonnett92** [comment]
It looks like a bug with the Android WebView yes, as Cordova are having the same issue [https://github.com/apache/cordova-android/issues/1465](https://github.com/apache/cordova-android/issues/1465)

**Comment by drasticactions** [comment]
Ignore that, I just finished reading the conversation, didn't notice what was discussed.

**Comment by mhrastegari** [comment]
You can get it using platform codes and use JSRuntime to set a value to a CSS variable! that's the solution we came for this issue.

**Comment by jbonnett92** [comment]
> You can get it using platform specific (MAUI Android) codes and use JSRuntime to set a value to a CSS variable! that's the solution we came for this issue.

I've tried that, didn't really work for me.

**Comment by mhrastegari** [comment]
We did it in our templates! everything you need to know is in [MainPage.xaml.cs](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/App/MainPage.xaml.cs#L81), [AppDeviceCoordinator.cs](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/App/Services/AppDeviceCoordinator.cs#L5), [App.razor.cs](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/App.razor.cs#L41) and [app.ts](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Scripts/app.ts#L21).

**Comment by jbonnett92** [comment]
> Still is progress but we did it in our templates! everything you need to know is in [MainPage.xaml.cs](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/App/MainPage.xaml.cs#L81), [AppDeviceCoordinator.cs](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/App/Services/AppDeviceCoordinator.cs#L5), [App.razor.cs](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/App.razor.cs#L41), [app.ts](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Scripts/app.ts#L21), [MainLayout.razor](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Shared/MainLayout.razor#L4) and [MainLayout.razor.scss](https://github.com/bitfoundation/bitplatform/blob/develop/src/Templates/TodoTemplate/Bit.TodoTemplate/src/Client/Core/Shared/MainLayout.razor.scss#L16).

That is too hacky for something that should be working within the framework, also looks like it requires extra dependencies.

**Comment by mhrastegari** [comment]
Agreed :"( this should be working within the framework.

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 2.1. Can repro on Android platforms with sample project.

**Comment by caliberdigitalllc** [comment]
What ended up being the next steps on this? I am having the same issues with 9p7.

![image](https://github.com/user-attachments/assets/ffc2cd88-841a-4300-b67a-e14485d6165e)

app.css:
body {
    padding-top: env(safe-area-inset-top);
    padding-left: env(safe-area-inset-left);
    padding-right: env(safe-area-inset-right);
    padding-bottom: env(safe-area-inset-bottom);
    margin: 0;
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    box-sizing: border-box;
}

index.html:
<body>

    <div class="status-bar-safe-area"></div>

    <div id="app">Loading...</div>

    <div id="blazor-error-ui">
        An unhandled error has occurred.
        <a href="" class="reload">Reload</a>
        <a class="dismiss">🗙</a>
    </div>

    <script src="_framework/blazor.webview.js" autostart="false"></script>

</body>

**Comment by Redth** [comment]
For now, you can revert to the old behaviour on android 35+ devices by following the workaround steps in the issue here:
#24742

**Comment by ne0rrmatrix** [comment]
I tried applying the fix above by @Redth but I still have an issue where webview is drawing over the bottom of the bar. I tested and it always draws over no matter what i do. Here is an image that is consistant regardless of anything I have done to make changes to android or maui. 

![Image](https://github.com/user-attachments/assets/3ccd867f-8574-4ff6-a2d8-61aa068611b0)

The Bottom bar is covering the text. I have tried many different approaches and nothing changes that bottom margin or bar. I am using webview on dotnet 9.x I am creating an open source ebook reader and this is one of the only issues I have left.

**Comment by mattleibow** [comment]
Android now respects the Safe Area rules, but is not so great out the box. However, a workaround is to tell android not to put things in dangerous places:

```xaml
SafeAreaEdges="{OnPlatform Android=Container, Default=None}"
```

iOS does not need this as the CSS seems to work.

Current State

| Android | |
|:-:|:-:|
| <img width="706" height="934" alt="Image" src="https://github.com/user-attachments/assets/fe564a25-910a-4a84-8a7e-fa635803a9d8" /> | <img width="1566" height="766" alt="Image" src="https://github.com/user-attachments/assets/c237621b-54a6-4ca8-83f5-7f75cc67393f" /> | 
| iOS | |
| <img width="752" height="928" alt="Image" src="https://github.com/user-attachments/assets/e11d2653-8856-4f70-8b8b-7e500ae8fdea" /> | <img width="1594" height="746" alt="Image" src="https://github.com/user-attachments/assets/719af2f1-310b-403a-98d7-2eb400886566" /> |
