### ISSUE TITLE
UI sometimes becomes uninteractive with the mouse after selecting a file from a file input (.NET MAUI Blazor)

### ISSUE THREAD

**Issue by DennisvHest** [dotnet/maui#15072]
### Description

Sometimes after selecting a file using a file input, the application can no longer be interacted with using the mouse. The application is not frozen however, because you can still interact with the keyboard.

It happens very inconsistantly. Sometimes I can reproduce it immediately, other times I have to select like 20 files before the bug occurs.

Once the bug occurs, the mouse interactivity can be restored by moving the mouse cursor out of the window. After that you can interact with the mouse again.

UPDATE (14-01-2024): After updating to .NET 8, instead of the original bug occuring, the application crashes.

https://github.com/dotnet/maui/assets/18610083/28ba1536-86ce-4245-acaf-636b8fd051b1

### Steps to Reproduce

1. Create a File > New .NET MAUI Blazor App
2. Add the following code to the index.razor page:
```
@page "/"

<input type="file" />
<b>Counter: @counter</b>
<button @onclick="IncrementCount">count</button>

@code {
    int counter = 0;

    void IncrementCount()
    {
        counter++;
    }
}
```
3. Select a file using the file input
4. Try to click the count button
5. If you can still click the count button, repeat steps 3 and 4 (it might take like 20 times for the bug to occur)
6. If the bug occurs (count button cannot be clicked), move the mouse outside of the window
7. The count button can now be clicked again

Expected outcome: page stays interactive
Actual outcome: page is no longer interactive using the mouse
.NET 8 Update: application now crashes when this occurs

### Link to public reproduction project repository

https://github.com/DennisvHest/FileInputBugTest

### Version with bug

8.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 10 22H2, Windows App SDK 1.3.230502000

### Did you find any workaround?

Haven't found a workaround for this.

**Comment by Makstvell** [comment]
I have same problem , when i fast input text to <input> and change focus to other <input>. App becomes uninteractive!!!

**Comment by DennisvHest** [comment]
> I have same problem , when i fast input text to and change focus to other . App becomes uninteractive!!!

@Makstvell I had this issue aswell at first, but this has been fixed in an update to the Windows App SDK. You will have to manually update this in your application.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3003#issuecomment-1499349079

This issue might be related. I wasn't sure where to post this issue. I only use webview2 via .NET MAUI Blazor.

**Comment by Makstvell** [comment]
@DennisvHest  Thank you very much. It works.

**Comment by mkArtakMSFT** [comment]
Thanks for helping out with this, @DennisvHest !

**Comment by DennisvHest** [comment]
@mkArtakMSFT Why is this closed? My comment to @Makstvell was about a different issue. That other issue was fixed, but this issue still persists.

**Comment by Makstvell** [comment]
@DennisvHest One more question, do you know how to fix when sometimes when open app -> black screen?

**Comment by Makstvell** [comment]
@mkArtakMSFT issue can't be closed, because other issue was fixed.

**Comment by DennisvHest** [comment]
> @DennisvHest One more question, do you know how to fix when sometimes when open app -> black screen?

@Makstvell No, I don't know. I have not experienced that issue in my project.

**Comment by Eilon** [comment]
There is this WebView2 issue with `<input type="file">` that can cause the app to crash: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3551

I wonder if the root issue is the same?

**Comment by Eilon** [comment]
Confirmed still repros with .NET 8.

**Comment by DennisvHest** [comment]
I have updated the reproduction project to .NET 8. Issue still persists, however now the application crashes instead of not being interactive using the mouse.

I cannot view the exception. Visual studio shows me this window:
![image](https://github.com/dotnet/maui/assets/18610083/0f82e544-e1d5-42ee-b355-3130da565bf5)

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. Not repro on windows platforms with sample project.
[FileInputBugTest-master.zip](https://github.com/dotnet/maui/files/13972788/FileInputBugTest-master.zip)
![15072](https://github.com/dotnet/maui/assets/77434865/b9f6501c-3991-4d4d-904e-af4123cab412)

**Comment by Eilon** [comment]
> I have updated the reproduction project to .NET 8. Issue still persists, however now the application crashes instead of not being interactive using the mouse.
> 
> I cannot view the exception. Visual studio shows me this window: ![image](https://private-user-images.githubusercontent.com/18610083/296609399-0f82e544-e1d5-42ee-b355-3130da565bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTI0ODgsIm5iZiI6MTcwNTcxMjE4OCwicGF0aCI6Ii8xODYxMDA4My8yOTY2MDkzOTktMGY4MmU1NDQtZTFkNS00MmVlLWIzNTUtMzEzMGRhNTY1YmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDAwNTYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZTlhNjE4NGRhYWVmZGRlYTBmOTJmNTc3MTE0MWI3YzFiZmUwZmVkNzUxNThhMTRjNTg1YjgxNzA4OTQ2MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iS2T73Ew-htz2cljxjidQVEzrbMkuc6EV1-hlNXUJ9E)

That is the behavior I 'expect' if the app is run with the debugger attached, and it's the issue I linked earlier: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3551

But I was able to repro the original issue when I ran the app _without_ the debugger attached. After closing the file dialog it would _sometimes_ ignore several mouse clicks.

They _could_ be the same underlying issue, but I'm not certain.

**Comment by Eilon** [comment]
This issue was moved to MicrosoftEdge/WebView2Feedback#4531
