### ISSUE TITLE
Blazor hybrid JS initializers dont work

### ISSUE THREAD

**Issue by Kebechet** [dotnet/maui#15201]
### Description

Blazor hybrid custom JS initializers `beforeStart` and `afterStarted` dont work.

Same files (just renamed .lib.module.js) work as expected in Blazor WASM.

### Steps to Reproduce

1) Run my repo on e.g. Windows machine
2) Open dev-tools
3) navigate to head tag in html document, and none of test1.js or test2.js are there. At the same time Console doesnt contain `console.logs` specified in JS module.

I suppose this worked on .NET 6 based on this issue: 
https://github.com/dotnet/maui/issues/7965#issuecomment-1163501960

### Link to public reproduction project repository

https://github.com/Kebechet/Bug-BlazorHybrid-js-initializers/tree/main/src

### Version with bug

7.0.59

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, Windows, macOS

### Affected platform versions

Windows 11 Pro 10.0.22621 Build 22621

### Did you find any workaround?

nope

**Comment by mkArtakMSFT** [comment]
This is potentially the same issue as https://github.com/dotnet/aspnetcore/issues/42349

**Comment by Jarek300** [comment]
What does modified milestones mean? If won't be fixed before .NET 8 release in November?

**Comment by Zhanglirong-Winnie** [comment]
Verified this issue with Visual Studio Enterprise 17.9.0 Preview 3. Can repro on windows platforms with sample project.
https://github.com/Kebechet/Bug-BlazorHybrid-js-initializers.git

**Comment by javiercn** [comment]
This should be fixed in https://github.com/dotnet/maui/pull/18953

**Comment by Kebechet** [comment]
> This should be fixed in #18953

nice, when the patch containing this fix should be released ?

**Comment by mrlife** [comment]
@javiercn, thanks for getting this fixed! Do you know if this will go out in a monthly patch or have to wait for .NET 9?

**Comment by Kebechet** [comment]
I checked and #18953 was released in [8.0.6 SR1](https://github.com/dotnet/maui/releases/tag/8.0.6)
So I updated to latest MAUI but this still doesnt work for me. 
@mrlife @Jarek300  can you give it a try as well ?

**Comment by mkArtakMSFT** [comment]
Thanks for your patience. This should be fixed in the latest .NET 8 SDK release. Please note, that the fix is int the Microsoft.AspNetCore.Components.WebView package, and if you have a direct reference to it from any of your projects, you should update it to the latest patch release.

**Comment by Kebechet** [comment]
1) can you please always write what is that latest version where it is released ?
2) It doesnt work for me. I have updated the repro package to latest .net8 with all packages and still I cant see those initializers working. I have added to the repro also Blazor project with the initializer renamed (based on assembly name) and there is works as expected. 

So either the newest fix is not released or it is not fixed

**Comment by AlexMountainBN** [comment]
I explicitly installed "Microsoft.AspNetCore.Components.WebView" in Version 8.0.4 and it's now working for me.

**Comment by Kebechet** [comment]
@AlexMountainBN 
you are right. Even updating `Microsoft.AspNetCore.Components.WebView.Maui` didnt fix this but after I explicitly installed the `Microsoft.AspNetCore.Components.WebView` in 8.0.4 it started to work.
