### ISSUE TITLE
[regression/8.0.0-preview.7.8842] Binding Issue: Multiple platform Slider control 'Value'

### ISSUE THREAD

**Issue by Stedy59** [dotnet/maui#16720]
### Description

Slider control ValueProperty will not update using a bound property.

### Steps to Reproduce

1. Create a Slider
2. Bind its Value property to a BindableProperty
3. Slider value remains at 0

### Link to public reproduction project repository

https://github.com/Stedy59/StedySoft.BindingIssues.1

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, Windows, I was *not* able test on other platforms

### Affected platform versions

Windows SDK - all, Android API 34

### Did you find any workaround?

No

**Comment by Stedy59** [comment]
Seriously???? You decide that binding to the core property of a core control is added to the backlog???

**Comment by jsuarezruiz** [comment]
Cannot reproduce the issue on current net8 branch with W11 22H2.
![issue-slider-net8](https://github.com/dotnet/maui/assets/6755973/bba41949-f894-46af-a472-a74110c92221)

**Comment by Stedy59** [comment]
![image](https://github.com/dotnet/maui/assets/46286656/6497cb58-a2da-46e7-a59c-9dab9022516f)

![ScreenCapture_4](https://github.com/dotnet/maui/assets/46286656/1159190a-af7f-4a89-bb5b-47f79abbaa96)

**Comment by Stedy59** [comment]
> Cannot reproduce the issue on current net8 branch with W11 22H2. ![issue-slider-net8](https://user-images.githubusercontent.com/6755973/260971790-bba41949-f894-46af-a472-a74110c92221.gif)

I don't think this issue is just with the slider control... Prior to the latest release, the core binding logic for two-way binding was modified. If you set a value to a control property, then attempt to bind the control, two way binding no longer works.... And guaranteed to fail if you use templated controls! 

I spend 4 days researching this, and creating multiple projects for your team.... One could reproduce this at will. Two way binding is broken... on multiple platforms.

**Comment by daltzctr** [comment]
I can also reproduce this.

**Comment by StephaneDelcroix** [comment]
should be fixed by #16410

**Comment by Stedy59** [comment]
> should be fixed by #16410

@StephaneDelcroix I am using the Nightly Builds. The last Maui nightly was August 10th. Any idea when this might be merged and a nightly build run. I would like to test ASAP to validate my code. Thank you for your attention on this.

**Comment by samhouts** [comment]
@Stedy59 We'll get a new nightly up as soon as possible. If this isn't fixed in the new build, let me know! Thanks!!

**Comment by developer9969** [comment]
is the above related to https://github.com/dotnet/maui/issues/16849 where it says that is not fixed
