### ISSUE TITLE
[Bug] Blazor Maui App not resizing with change of window size

### ISSUE THREAD

**Issue by igalfsg** [dotnet/maui#1730]
### Description
When a window is resized the blazor app does not respond as it should (collapsing the nav bar, shrinking the components etc).

### Steps to Reproduce
1. Create a Maui Blazor App 
2. Resize the window

### Expected Behavior
The Blazor application should behave like it does in the browser and adjust to the screen size. 
### Actual Behavior
It doesn't change the component sizes. 
### Basic Information

Version with issue: preview 6
Last known good version: N/A
IDE:Microsoft Visual Studio Community 2019 Preview
Version 16.11.0 Preview 3.0

**Comment by pjmagee** [comment]
I can confirm this happens with the latest BlazorWeather app: https://github.com/danroth27/BlazorWeather

I'm pretty sure in the past when this was shown on Stream and previous demo's the App was responsive. But maybe my mind is fooling me?

**Comment by pjmagee** [comment]
Made a workaround with #1732

**Comment by Eilon** [comment]
@igalfsg can you show screenshots or a video of what isn't resizing? And any CSS you have? If you have the appropriate CSS media queries for screen size/width then it should all work fine.

Here's what a default Blazor template looks like in .NET MAUI:

Wide UI, menu expanded on the left:
![image](https://user-images.githubusercontent.com/202643/128392286-aff90d42-55fc-494a-98c8-5df7c56f7aa1.png)

Narrow UI, menu collapsed at top:
![image](https://user-images.githubusercontent.com/202643/128392321-8eb1eb43-bbce-443e-b6be-f2ecec3004a4.png)

Note: I'm running on the latest dev bits, so there could be some fixes in there that you might not yet have, but I can't think of anything that would affect this particular case.

**Comment by pjmagee** [comment]
If it no longer happens with the default Weather app then I guess it is fixed? I believe that did have css queries to make it responsive?

**Comment by igalfsg** [comment]
Hi Eilon, 

here are the screenshots:
![image](https://user-images.githubusercontent.com/8607853/128699053-1ddde4fa-71c9-4988-9e82-b84a94d2b87d.png)
![image](https://user-images.githubusercontent.com/8607853/128699076-a2470a02-f395-43c6-9c0b-b8b0ef8e12a5.png)

I updated to the latest externally available Nuget packages and it is still occurring.

**Comment by Eilon** [comment]
@igalfsg - interesting. In your case it looks like the web view is not being resized at all because the HTML is visually cut off on the right side. I'm not sure why that's happening, but that would explain why the contents of the HTML are not being wrapped.

**Comment by igalfsg** [comment]
This was on a fresh template, I will wait for the preview 7 to be released and try it on a fresh project then to see if this is solved.

**Comment by pjmagee** [comment]
> @igalfsg - interesting. In your case it looks like the web view is not being resized at all because the HTML is visually cut off on the right side. I'm not sure why that's happening, but that would explain why the contents of the HTML are not being wrapped.

And this is why my hack works to fix this. Because i experience the same issue.

**Comment by Eilon** [comment]
@pjmagee there certainly could have been some bug in the layout controls. I wonder what happens if you places the BlazorWebView in some other container, such as a StackLayout. DOes that make it resize itself?

**Comment by igalfsg** [comment]
Update on my side, updated to the latest bits and it now resizes

**Comment by Eilon** [comment]
Great to hear, thank you for the update!

**Comment by Eilon** [comment]
Hi everyone, as far as I know all these issues are fixed for the next preview. I used to see such issues myself a while ago but not recently in the `main` branch of this repo, either in the dev solution, or using the project templates that I built locally. As such, I am closing this issue. But if someone sees any such issue after the next preview (should be this month), I would love to hear about it and make sure we address any remaining issues.
