### ISSUE TITLE
Entry Completed Event Triggered Twice

### ISSUE THREAD

**Issue by SethupathyD** [dotnet/maui#27992]
### Description

When setting ReturnType="Search" in an Entry on Android, the return key type does not update properly. To work around this, I used EntryHandler.Mapper.AppendToMapping to ensure UpdateReturnType(view) is called when the view is attached to the window. However, this causes the Completed event to fire twice—once for the actual return key press and once due to the view being updated dynamically.

![Image](https://github.com/user-attachments/assets/60811485-f0d8-4873-97d7-4bb55205559a)

### Steps to Reproduce

Steps to reproduce

1. Run the app on an Android device or emulator.
2. Tap on the Entry, type something, and press the return key.

Expected Behavior
The return key should immediately display as "Search" when the ReturnType is set.
The Completed event should fire only once when the return key is pressed.

Actual Behavior
The return key does not initially show "Search" unless modified using EntryHandler.Mapper.
The Completed event fires twice when pressing the return key.

### Link to public reproduction project repository

https://github.com/SethupathyD/EntryTypeIssue

### Version with bug

8.0.83 SR8.3

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 11

### Did you find any workaround?

Used mapping as a work around but entry completed event gets trigerred twice.

### Relevant log output

```shell

```

**Comment by bhavanesh2001** [comment]
@SethupathyD This is fixed with [this](https://github.com/dotnet/maui/pull/26501) in 9.0.30

**Comment by Ying-6** [comment]
This issue has been verified using Visual Studio 17.14 Preview 1(9.0.40 & 9.0.21 & 9.0.0). Can repro this issue on Windows platform. 
![Image](https://github.com/user-attachments/assets/e53f0d00-8315-4edc-9c71-8e4f1471654c)

**Comment by jfversluis** [comment]
Please try with the latest .NET 9 version, at the time of writing 9.0.40 and see how that changes the behavior and if that solves your problem. Thanks!

**Comment by SethupathyD** [comment]
Hi @jfversluis ,

I have verified that with the latest version (9.0.40) on the Android platform. Setting ReturnType="Search" works without appendToMapping, but the issue still persists—the Completed event is triggered twice when performing a search on Android.

Regards,
Sethupathy D.

**Comment by bhavanesh2001** [comment]
@SethupathyD Please modify title accordingly

**Comment by jfversluis** [comment]
@Ying-6 @SethupathyD does this also happen on other platforms like Windows or iOS or only on Android?

**Comment by Ying-6** [comment]
@jfversluis This issue does not repro on iOS and Windows platforms on 9.0.40.
