### ISSUE TITLE
AppShell no longer working on iOS 26

### ISSUE THREAD

**Issue by vtserej** [dotnet/maui#31982]
### Description

I recently had my app denied in the appstore due to a alleged crash on start on iOS 26.
Upon checking in my local Mac I noticed that on iOs 26 emulator my App gets stuck on the Splash Screen.
I tried the Maui default robot project and I noticed it happens there as well. 

### Steps to Reproduce

1. Create a new iOS maui app - Xcode 26.1, Maui 9, .net SDK 9.0.200. Arm Mac
2. Run the project and find a black screen.
3. If you have a project that does not use AppShell it will work fine.

### Version with bug

9.0.110 SR11

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Affected platforms

iOS

### Affected platform versions

ios26

### Did you find any workaround?

No workaround but if you replace your CreateWindow code with this it will show content

`protected override Window CreateWindow(IActivationState? activationState)
{
    var label = new Label
    {
        Text = "Hello",
        HorizontalOptions = LayoutOptions.Center,
        VerticalOptions = LayoutOptions.Center,
        FontSize = 24
    };

    var page = new ContentPage
    {
        Content = new Grid
        {
            Children = { label }
        },
        BackgroundColor = Colors.White
    };

    return new Window(page);
}`

### Relevant log output

```shell
No relevant log output.
the Home screen inside the Shell app gets its events triggered (navigated and onappearing)
```

**Comment by StephaneDelcroix** [comment]
`dotnet new maui` on net10.0-rc1 doesn't crash on an iOS sim

could you try net10.0 ?

**Comment by jfversluis** [comment]
That sounds very much like the thing we fixed here: https://github.com/dotnet/maui/pull/31149 which was also back ported to .NET 9 and part of 9.0.110. However that was with Xcode 26 and not 26.1, although I would think its unlikely that they would have introduced another change like this, but its not impossible.

Are you very sure you are on 9.0.110? Can you share the project? Even if its just the File > New MAUI app?

**Comment by vtserej** [comment]
I was using Version="$(MauiVersion)"/> which I assumed used the latest release. After setting it up to 9.0.110 the problem was fixed. thank you.

**Comment by michaelshodamola** [comment]
I am having same issue on 9.0.306.

**Comment by vtserej** [comment]
Just target MAUI 9.0.110

**Comment by jfversluis** [comment]
A small addition, you can add

```xml
<key>UIDesignRequiresCompatibility</key>
<true/>
```

To your info.plist file and that will make it fall back for now. But Apple will probably remove this as soon as they can (iOS 27?!) so you better still get updating :)

**Comment by hannerygge** [comment]
> A small addition, you can add
> 
> <key>UIDesignRequiresCompatibility</key>
> <true/>
> To your info.plist file and that will make it fall back for now. But Apple will probably remove this as soon as they can (iOS 27?!) so you better still get updating :)

I tried setting the maui version, which didn't stop the crashing, but setting UIDesignRequiresCompatibility solved it for me.

**Comment by Detrua** [comment]
> A small addition, you can add
> 
> <key>UIDesignRequiresCompatibility</key>
> <true/>
> To your info.plist file and that will make it fall back for now. But Apple will probably remove this as soon as they can (iOS 27?!) so you better still get updating :)

It worked for me too. Thank you so much — you've just saved my day!

**Comment by dmn8s5** [comment]
> A small addition, you can add
> 
> <key>UIDesignRequiresCompatibility</key>
> <true/>
> To your info.plist file and that will make it fall back for now. But Apple will probably remove this as soon as they can (iOS 27?!) so you better still get updating :)

This worked for me as well. Thank you!

**Comment by KevThompson2020** [comment]
UIDesignRequiresCompatibility fixed it for me but things seem to be changing.  Builds that were working last week on TestFlight stopped working today.
