### ISSUE TITLE
IServiceProvider is disposed with new Maui Project @ Android

### ISSUE THREAD

**Issue by Mafyou** [dotnet/maui#32750]
### Description

An explosion when go back

### Steps to Reproduce

1. Create Maui project with dotnet 10
2. Run
3. Go backward
=> [System.ObjectDisposedException]: Cannot access a disposed object. Object name: 'IServiceProvider'.

### Link to public reproduction project repository

https://github.com/Mafyou/ArchiDesignPatterns

### Version with bug

10.0.10

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

10.0.10

### Affected platforms

Android

### Affected platform versions

Android API 35

### Did you find any workaround?

Nothing. I'm totally blocked

### Relevant log output

```shell
11-19 18:09:08.769 E/AndroidRuntime(16663): FATAL EXCEPTION: main
11-19 18:09:08.769 E/AndroidRuntime(16663): Process: fr.mattd.archidesignpatterns, PID: 16663
11-19 18:09:08.769 E/AndroidRuntime(16663): android.runtime.JavaProxyThrowable: [System.ObjectDisposedException]: Cannot access a disposed object.
11-19 18:09:08.769 E/AndroidRuntime(16663): Object name: 'IServiceProvider'.
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException + 0x0(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService + 0x8(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Maui.MauiContext+WrappedServiceProvider.GetService(/_/src/Core/src/MauiContext.cs:87)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Maui.MauiContext+WrappedServiceProvider.GetService(/_/src/Core/src/MauiContext.cs:87)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService + 0x28(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService + 0xb(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Maui.MauiContextExtensions.GetDispatcher(/_/src/Core/src/MauiContextExtensions.cs:33)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Maui.Controls.Platform.Compatibility.ShellFragmentContainer.OnDestroy(/_/src/Controls/src/Core/Compatibility/Handlers/Shell/Android/ShellFragmentContainer.cs:43)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at AndroidX.Fragment.App.Fragment.n_OnDestroy(C:\a\_work\1\s\generated\androidx.fragment.fragment\obj\Release
et10.0-android\generated\src\AndroidX.Fragment.App.Fragment.cs:2465)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw + 0x11(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualVoidMethod + 0x86(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod + 0x65(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Android.App.Activity.OnDestroy + 0x0(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Microsoft.Maui.MauiAppCompatActivity.OnDestroy(/_/src/Core/src/Platform/Android/MauiAppCompatActivity.cs:49)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at Android.App.Activity.n_OnDestroy + 0xe(Unknown Source)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.n_onDestroy(Native Method)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at crc6488302ad6e9e4df1a.MauiAppCompatActivity.onDestroy(MauiAppCompatActivity.java:59)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.Activity.performDestroy(Activity.java:9310)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1573)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6032)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6077)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:52)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleItem(TransactionExecutor.java:169)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:101)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.os.Handler.dispatchMessage(Handler.java:109)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.os.Looper.loopOnce(Looper.java:232)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.os.Looper.loop(Looper.java:317)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at android.app.ActivityThread.main(ActivityThread.java:8783)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at java.lang.reflect.Method.invoke(Native Method)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:595)
11-19 18:09:08.769 E/AndroidRuntime(16663): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)
An error occurred in the vsdbg debug session of project 'D:\source\ArchiDesignPatterns\src\ArchiDesignPatterns.Mobile\ArchiDesignPatterns.Mobile.csproj': An unhandled exception of type 'Android.Runtime.JavaProxyThrowable' occurred in Mono.Android.Runtime.dll
The program 'ArchiDesignPatterns.Mobile.dll' has exited with code 0 (0x0).
The vsdbg debug session for project 'D:\source\ArchiDesignPatterns\src\ArchiDesignPatterns.Mobile\ArchiDesignPatterns.Mobile.csproj' has been stopped
```

**Comment by LogishaSelvarajSF4525** [comment]
This issue has been validated in Visual Studio Code 1.106.2 with MAUI versions 9.0.120, 10.0.0-preview.1, 10.0.0-rc.1, 10.0.0-rc.2, 10.0.0 & 10.0.10. It can be reproducible from 10.0.0-rc.1 on Android platform and was not reproducible below .net10-rc1 versions.

**Comment by dmm-l-mediehus** [comment]
Hello, this issue is coming from Android 15 with their new predictive back gesture behavior: https://developer.android.com/guide/navigation/custom-back/predictive-back-gesture#update-custom

As a workaround, disable it by navigating to MainActivity.cs under Android platforms folder, add to the ActivityAttribute:
`EnableOnBackInvokedCallback = false`.

A PR is ongoing: https://github.com/dotnet/maui/pull/32461

**Comment by Mafyou** [comment]
Thank you @dmm-l-mediehus.
Tried this tips, but still the same.
I hope PR'll be accepted fast because my business is based on Maui.

**Comment by aksik** [comment]
Exactly the same happen when you run android task manager and close app from there - it crash the same way.
Would it also be fixed with this pr?
Or should I create another issue for this scenario?

**Comment by gwise-vision** [comment]
11-25 14:57:19.985 E/AndroidRuntime(22615): android.runtime.JavaProxyThrowable: [System.ObjectDisposedException]: Cannot access a disposed object.

11-25 14:57:19.985 E/AndroidRuntime(22615): Object name: 'IServiceProvider'.

**Comment by kubaflo** [comment]
Hi! It is fixed by this PR https://github.com/dotnet/maui/pull/32461

**Comment by DashTheDev** [comment]
> Hi! It is fixed by this PR [#32461](https://github.com/dotnet/maui/pull/32461)

Is the `Cannot access a disposed object. Object name: 'IServiceProvider'` issue not related to #32647 instead? I used the code from #32461, both via the PR and via the latest SR release, and the exception on quit still exists. That PR (#32461) does fix navigation behavior on newer Android APIs, but I don't think it fixes the crash on app close.

Although I could be mistaken, could I get some clarification on that?

**Comment by kubaflo** [comment]
@DashTheDev you're right! I remember there were 2 PR's related to this exception. I think this one will be helpful to you :)
https://github.com/dotnet/maui/pull/32647

**Comment by maonaoda** [comment]
I have no use for Shell, but this problem also occurs constantly.

**Comment by johnhoven** [comment]
Hello, any chance this/#32647 can be backported to SR1?  

We've tried 10.0.11 package that should contain https://github.com/dotnet/maui/pull/32461 and tried setting EnableOnBackInvokedCallback = false on the Activity.  

We still crash on Android with this exception when:
- Launching camera (MediaPicker.Default.CapturePhotoAsync)
- Launching photo picker (MediaPicker.Default.PickPhotoAsync)
- Launching maps/driving directions (Microsoft.Maui.ApplicationModel.Map.OpenAsync)

Edit: On further research, I believe this was a little exaggerated and likely more limited to users with lower end devices.  My emulator was set to Don't Keep Activities which made it 100% reproducible for all these callout scenarios.   I've been able to downgrade to MAUI 9 until SR2 is available.

**Comment by chrismcna** [comment]
a work around,
override OnDestroy on activity

```
 protected override void OnDestroy()
 {
     try
     {
         base.OnDestroy();
     }
     catch (Exception e)
     {

     }
 }
```

**Comment by aksik** [comment]
> a work around, override OnDestroy on activity
> 
> ```
>  protected override void OnDestroy()
>  {
>      try
>      {
>          base.OnDestroy();
>      }
>      catch (Exception e)
>      {
> 
>      }
>  }
> ```

It's not the best workaround because it will crash next time you want to run an app :/
This problem stops us from migrating to .net10 - how can you make a production app if even sample app crash :/

does anyone have any idea when it will be fixed?

**Comment by FSofTlpz** [comment]
My workaround:
A class for the (new) Backbutton-Handling

```
   public class OnBackbuttonPressedCallback : OnBackPressedCallback {
      private readonly Activity activity;

      public class PressedEventArgs : EventArgs {

         public bool ShouldAppClose { get; private set; }

         public bool Cancel { get; set; }

         public PressedEventArgs(bool shouldAppClose) {
            ShouldAppClose = shouldAppClose;
            Cancel = false;
         }
      }

      public static event EventHandler<PressedEventArgs>? OnPressed;


      public OnBackbuttonPressedCallback(Activity activity) : base(true) {
         this.activity = activity;
      }

      public override void HandleOnBackPressed() {
         var navigation = Microsoft.Maui.Controls.Application.Current?.Windows[0].Page?.Navigation;
         bool cancel = false;
         if (navigation is not null &&
             navigation.NavigationStack.Count <= 1 &&
             navigation.ModalStack.Count <= 0) {
            if (OnPressed is not null) {
               var args = new PressedEventArgs(true);
               OnPressed?.Invoke(this, args);
               cancel = args.Cancel;
            }
            if (!cancel) {
               activity.FinishAndRemoveTask();
               Process.KillProcess(Process.MyPid());
            }
         } else {
            if (OnPressed is not null) {
               var args = new PressedEventArgs(true);
               OnPressed?.Invoke(this, args);
               cancel = args.Cancel;
            }
            if (!cancel)
               navigation?.PopAsync();
         }
      }
   }
```

In the MainActivity
```
     protected override void OnCreate(Bundle? savedInstanceState) {
        base.OnCreate(savedInstanceState);
        OnBackPressedDispatcher.AddCallback(this, new OnBackbuttonPressedCallback(this));
       ...
```

The Problem is, that App.OnSleep() is not more called. I need this, that's why in my MainPage for last Actions:

```
            OnBackbuttonPressedCallback.OnPressed += (s, e) => {
               if (e.ShouldAppClose) {
                  ...
               }
            };

```

**Comment by F30Boy** [comment]
Will this be released on Jan 13th as part of Patch Tuesday?

**Comment by idiidi** [comment]
I have updated to 10.0.20 but I still have this issue

**Comment by holecekp** [comment]
I got the same exception even in the latest 10.0.30.

**Comment by brzezinol** [comment]
Problem still exists.
`android 36.1.2/10.0.100 `

`02-11 08:47:56.379 E/AndroidRuntime(21987): FATAL EXCEPTION: main
02-11 08:47:56.379 E/AndroidRuntime(21987): Process: com.xxx, PID: 21987
02-11 08:47:56.379 E/AndroidRuntime(21987): android.runtime.JavaProxyThrowable: [System.ObjectDisposedException]: Cannot access a disposed object.
02-11 08:47:56.379 E/AndroidRuntime(21987): Object name: 'IServiceProvider'.`

----
Edit
after `dotnet workloads update` it seems to work properly.
