### ISSUE TITLE
[Bug] 'DllNotFoundException: libcoreclr.so' when I attempt to perform a login through iOS

### ISSUE THREAD

**Issue by ElliottBrand** [dotnet/maui#3406]
If I attempt to perform a login to my API from within the iOS platform (MAUI Blazor), an exception is thrown:

```
System.DllNotFoundException: libcoreclr.so
   at Interop.AppleCrypto.GetRandomBytes(Byte* pbBuffer, Int32 count) in System.Security.Cryptography.Algorithms.dll:token 0x600002e+0x0
...
```

- Using Visual Studio 2022 Preview Version 17.1.0 Preview 1.0
- I'm pared to an iPhone as the iOS Local Device.
- I've tried both hitting a local IPv4 based http endpoint and production/live https endpoint.

**Comment by ElliottBrand** [comment]
Here's a more detailed message:

```
{System.DllNotFoundException: libcoreclr.so
   at Interop.AppleCrypto.GetRandomBytes(Byte* pbBuffer, Int32 count) in System.Security.Cryptography.Algorithms.dll:token 0x600002e+0x0
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte* pbBuffer, Int32 count) in System.Security.Cryptography.Algorithms.dll:token 0x60001c3+0x0
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Span`1 data) in System.Security.Cryptography.Algorithms.dll:token 0x60001c0+0x15
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte[] data) in System.Security.Cryptography.Algorithms.dll:token 0x60001be+0xe
   at IdentityModel.CryptoRandom.CreateRandomKey(Int32 length) in IdentityModel.dll:token 0x600000c+0x7
   at IdentityModel.CryptoRandom.CreateUniqueId(Int32 length, OutputFormat format) in IdentityModel.dll:token 0x600000d+0x0
   at IdentityModel.OidcClient.CryptoHelper.CreatePkceData() in IdentityModel.OidcClient.dll:token 0x6000015+0x15
   at IdentityModel.OidcClient.AuthorizeClient.CreateAuthorizeState(Parameters frontChannelParameters) in IdentityModel.OidcClient.dll:token 0x6000004+0x15
   at IdentityModel.OidcClient.AuthorizeClient.AuthorizeAsync(AuthorizeRequest request, CancellationToken cancellationToken) in IdentityModel.OidcClient.dll:token 0x6000002+0x41
   at IdentityModel.OidcClient.OidcClient.LoginAsync(LoginRequest request, CancellationToken cancellationToken) in IdentityModel.OidcClient.dll:token 0x6000021+0x15b
   at Blazot.MauiStation.Services.LoginService.LoginAsync() in C:\[xxxxxxxxx]\Services\LoginService.cs:line 61}
```

Line 61 is just performing a login request.  _result is an IdentityModel OidcClient LoginResult, and _client is OidcClient.

```
_result = await _client.LoginAsync(new LoginRequest());
```

**Comment by ElliottBrand** [comment]
Here's a more detailed message:

```
{System.DllNotFoundException: libcoreclr.so
   at Interop.AppleCrypto.GetRandomBytes(Byte* pbBuffer, Int32 count) in System.Security.Cryptography.Algorithms.dll:token 0x600002e+0x0
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte* pbBuffer, Int32 count) in System.Security.Cryptography.Algorithms.dll:token 0x60001c3+0x0
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Span`1 data) in System.Security.Cryptography.Algorithms.dll:token 0x60001c0+0x15
   at System.Security.Cryptography.RandomNumberGeneratorImplementation.GetBytes(Byte[] data) in System.Security.Cryptography.Algorithms.dll:token 0x60001be+0xe
   at IdentityModel.CryptoRandom.CreateRandomKey(Int32 length) in IdentityModel.dll:token 0x600000c+0x7
   at IdentityModel.CryptoRandom.CreateUniqueId(Int32 length, OutputFormat format) in IdentityModel.dll:token 0x600000d+0x0
   at IdentityModel.OidcClient.CryptoHelper.CreatePkceData() in IdentityModel.OidcClient.dll:token 0x6000015+0x15
   at IdentityModel.OidcClient.AuthorizeClient.CreateAuthorizeState(Parameters frontChannelParameters) in IdentityModel.OidcClient.dll:token 0x6000004+0x15
   at IdentityModel.OidcClient.AuthorizeClient.AuthorizeAsync(AuthorizeRequest request, CancellationToken cancellationToken) in IdentityModel.OidcClient.dll:token 0x6000002+0x41
   at IdentityModel.OidcClient.OidcClient.LoginAsync(LoginRequest request, CancellationToken cancellationToken) in IdentityModel.OidcClient.dll:token 0x6000021+0x15b
   at xxxxxxxxx.Services.LoginService.LoginAsync() in C:\[xxxxxxxxx]\Services\LoginService.cs:line 61}
```

Line 61 is just performing a login request.  _result is an IdentityModel OidcClient LoginResult, and _client is OidcClient.

```
_result = await _client.LoginAsync(new LoginRequest());
```

**Comment by ElliottBrand** [comment]
This seems to be limited to instances where I'm debugging on a local iPhone in Windows. When I pair Visual Studio to a Mac and debug through an iOS simulator phone, it doesn't throw the error.

**Comment by Eilon** [comment]
Recent dup of this issue here: https://github.com/dotnet/maui/issues/3505

**Comment by Eilon** [comment]
Looks like this was fixed for .NET 6 RC1 as part of this PR: https://github.com/xamarin/xamarin-macios/pull/12323 (I followed a trail starting at https://github.com/dotnet/runtime/issues/58185)

**Comment by Eilon** [comment]
BTW if for some reason this still occurs on the most recent builds, please file an issue at https://github.com/xamarin/xamarin-macios with the details and versions you are running.

**Comment by bwoebi** [comment]
@Eilon The issue is that Xamarin Hot restart does not have support for linking. Thus not including the crucial native libraries for crypto.

And I could not figure out how to use Pair to Mac with MAUI…

**Comment by Eilon** [comment]
@bwoebi OK. I'm not really an expert in this area, but I think that if there's an issue around this, it would still be best in https://github.com/xamarin/xamarin-macios because that's where this work is being done.

I'm not sure of the status of Pair to Mac. I thought I saw someone had it working, but I haven't tried it recently with my Mac. It's certainly planned to be fully working before release.

**Comment by ElliottBrand** [comment]
The issue still occurs for me when deploying straight from PC to iPhone, but I've been able to deploy to the iPhone through the mac when my PC is paired to it and that works well after all the certificates and everything are setup.

**Comment by Eilon** [comment]
@ElliottBrand got it.

If you have any remaining issues with the _runtime_ (such as missing `*.so` files), those need to be filed at https://github.com/xamarin/xamarin-macios.

If you have remaining issues with Visual Studio, please use the [VS feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) to report the issue. That way it will get to the routed to the right that owns this experience in VS. If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.
