### ISSUE TITLE
DisplayActionSheet not opening the action dialog on Windows

### ISSUE THREAD

**Issue by joshfourbadideas** [dotnet/maui#3726]
### Description

Just attempting to use the `Page.DisplayActionSheet` API on a MAUI content page and it isn't displaying the action sheet dialog at all.  The returned task never finishes, so it seems like it thinks it is rendered.  I can continue using the application as well, so navigation still seems fine too.

### Steps to Reproduce

1. Create a .NET MAUI App
2. Add a call to `Page.DisplayActionSheet`, for instance:
`await this.DisplayActionSheet("What type of condition?", "Cancel", null, "Source Condition", "Position Condition", "Attribute Condition", "Affected By Condition" );`
3. Observe the call never returns and the dialog is never displayed

### Version with bug

Preview 10 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

net6.0-windows10.0.19041

### Did you find any workaround?

No known workaround at this time.

**Comment by jsuarezruiz** [comment]
Could you attach a small sample where reproduce the issue?, are you trying to display the ActionSheet from the page constructor?

**Comment by joshfourbadideas** [comment]
I put the call in OnAppearing() on the page.

After looking at #15 it appears this just hasn't been completed in Preview 10 yet.

**Comment by joshfourbadideas** [comment]
So the issue seems to be with wrapping everything in a `NavigationPage` in the App.xaml.cs.  I did this because modal dialogs and things aren't working with MAUI on Windows yet, so I reverted to using `NavigationPage` to allow me to switch UI pages.

When this is done, HandlerExtensions.ToNative() for Windows is returning a `FrameworkElement` with a `ContentPanel` as the `Parent` property of my `ContentPage` instead of the `NavigationPage`.

I'm not sure if `NavigationPage` is fundamentally incompatible with `Page.DisplayActionSheet`.  Ultimately these wouldn't be necessary if modal dialogs were working.

**Comment by davidortinau** [comment]
Same issue here on WeatherTwentyOne

https://github.com/davidortinau/WeatherTwentyOne/blob/main/src/WeatherTwentyOne/Pages/SettingsPage.xaml.cs#L21

**Comment by shimingsg** [comment]
Verified Repro with windows, Repro project available in Maui Triage Teams channel:
https://microsoft.sharepoint.com/:u:/t/Mauitriage/EfrrzQUo9RRIiKy3oDRektMBF_iLaugCyWTP5NLQkvmAfQ?e=dzNmri

**Comment by Zetthard** [comment]
It seems to me, that issue is still present. I'm unable to DisplayActionSheet, while DisplayAlert works just fine from the same event handler.
`private async void DeviceDoubleTap_Tapped(object sender, EventArgs e)
    {
        await DisplayAlert("Alert", "AlertMessage", "ok");

        string action = await DisplayActionSheet("Menu", "Cancel", "Delete", "Configure", "Info");
    }`

**Comment by cshung** [comment]
> It seems to me, that issue is still present. I'm unable to DisplayActionSheet, while DisplayAlert works just fine from the same event handler. `private async void DeviceDoubleTap_Tapped(object sender, EventArgs e) { await DisplayAlert("Alert", "AlertMessage", "ok");
> 
> ```
> string action = await DisplayActionSheet("Menu", "Cancel", "Delete", "Configure", "Info");
> ```
> 
> }`

On what version are you testing it? The fix is merged in the main branch, can you test it on the main branch?

**Comment by Zetthard** [comment]
> g

I've got this result building and running MAUI project from VS 2022 version 17.2.0 Preview 2.1 with MAUI preview 14 installed with the latest VS update.
_dotnet --version_: 6.0.300-preview.22154.4

I've also tested it on MacOS, using CLI SDK installaton option (main branch), so I have 6.0.300-preview.22179.2 there. And this function works there as expected (both - maccatalyst and iOS builds).

**Comment by Zetthard** [comment]
> > It seems to me, that issue is still present. I'm unable to DisplayActionSheet, while DisplayAlert works just fine from the same event handler. `private async void DeviceDoubleTap_Tapped(object sender, EventArgs e) { await DisplayAlert("Alert", "AlertMessage", "ok");
> > ```
> > string action = await DisplayActionSheet("Menu", "Cancel", "Delete", "Configure", "Info");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }`
> 
> On what version are you testing it? The fix is merged in the main branch, can you test it on the main branch?

I've got this result building and running MAUI project from VS 2022 version 17.2.0 Preview 2.1 with MAUI preview 14 installed with the latest VS update.
_dotnet --version_: 6.0.300-preview.22154.4

I've also tested it on MacOS, using CLI SDK installaton option (main branch), so I have 6.0.300-preview.22179.2 there. And this function works there as expected (both - maccatalyst and iOS builds).

**Comment by cshung** [comment]
> I've got this result building and running MAUI project from VS 2022 version 17.2.0 Preview 2.1 with MAUI preview 14 installed with the latest VS update. _dotnet --version_: 6.0.300-preview.22154.4
> 
My fix narrowly missed preview 14

Here is the commit for the fix
```
commit fffaae1eaa33db6eeced93f0a85fc00cd155be19 (HEAD)
Author: Andrew Au <andrewau@microsoft.com>
Date:   Wed Mar 9 10:16:37 2022 -0800

    DisplayActionSheet later (#5047)
    
    * DisplayActionSheet later
    
    * - update loaded wiring on handler changed
    
    * Clean up/fix old iOS alert code
    
    We were previously creating new UIWindows presumably for some historic use case... This removes that and uses the window that's passed into the manager when created.
    
    * - change to using NavigatedTo
    
    Co-authored-by: redth <jondick@gmail.com>
    Co-authored-by: Shane Neuville <shneuvil@microsoft.com>
```

And here is the commit for preview 14.
```
commit 03a0eb8e69ecf81174f3346ce2050e021360d705 (tag: 6.0.200-preview.14.2, upstream/release/6.0.2xx-preview14)
Author: dotnet-maestro[bot] <42748379+dotnet-maestro[bot]@users.noreply.github.com>
Date:   Mon Mar 7 13:20:03 2022 -0500

    Update dependencies from https://github.com/xamarin/xamarin-macios build 20220306.16 (#5096)
    
    Microsoft.tvOS.Sdk , Microsoft.macOS.Sdk , Microsoft.MacCatalyst.Sdk , Microsoft.iOS.Sdk
     From Version 15.2.302-preview.14.91 -> To Version 15.2.302-preview.14.116
    
    Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
```

Note that preview 14 was on 7th of March while my fix merged on 9th of March, the fix does not make preview 14, that is why you still see the bug repros on preview 14.

**Comment by plettb** [comment]
I'm running VS 17.2.0 Preview 5 and I'm still experiencing this problem.  Is it something I'm doing wrong?
