### ISSUE TITLE
Pre11, Visual Studio 2022 Mac- "The application has not been built" error

### ISSUE THREAD

**Issue by lhughey** [dotnet/maui#3961]
### Description

I'm seeing an error when attempting to build and run the MauiPreview app in Mac VS 2022 Preview. This issue happens with both iOS and Android. The error is as follows and displays in a modal
`The application has not been built`

The build output shows that the build succeeded. Here is that output:
```
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:08.74

========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

I am confident I have the proper workload and configuration installed because I can start the app using the CLI command of 
`dotnet build -t:Run -f net6.0-ios /p:_DeviceName=:v2:udid=<UDID>`

i'm running:
- VS Mac 2022
- Xcode 13.2.1

### Steps to Reproduce

1. install vs 2022 preview on Mac Monterey (preview 11)
2. install the Maui workload - latest
3. dotnet new maui
4. open app in VS
5. select simulator from the target dropdown. Click start
6. See error
7. Verify the app runs in CLI by using `dotnet build -t:Run -f net6.0-ios /p:_DeviceName=:v2:udid=<UDID>`

### Version with bug

Preview 11

### Last version that worked well

Unknown/Other

### Affected platforms

iOS, Android, I was *not* able test on other platforms

### Affected platform versions

ios 15.2, android 11

### Did you find any workaround?

No.

**Comment by AnthonySlay** [comment]
@lhughey, I ran into this yesterday after installing the maui workload.  You will need to create a provisioning profile using xcode if you haven't already.  See this stackoverflow post at the link below for tips on how to do this.

https://stackoverflow.com/questions/49758320/could-not-find-any-available-provisioning-profiles-for-ios/50724757

I believe if you have a paid apple developer account (I don't), you can skip creating a provisioning profile and sign into your developer's account via Visual Studio > Preferences > Publishing > Apple Developer Accounts.  Sign in and select your team.  Save. Restart. Rebuild and it should just work.

**Comment by lhughey** [comment]
@AnthonySlay. That resolved this error message but not the issue. VS is not compiling changes though it seems to build and launches the app in the sim.

**Comment by AnthonySlay** [comment]
Yikes!  I'm getting the same behavior when modify C# files.  Modifying the MainPage.xaml file does show updates after a debugger stop and start though.  I'm not a maui maintainer but I'll see if I can't get past this bump in the road tonight.

**Comment by lhughey** [comment]
> 

I'm seeing this behavior in the xaml and cs files. I tried deleting and reinstalling VS with no change. :(

**Comment by AnthonySlay** [comment]
@lhughey looks like todays update to Xamarin.IOS 15.2.0.17 fixed this issue.  Thank goodness!

**Comment by AnthonySlay** [comment]
@lhughey scratch that, it might have been because I turned off hot reload and rebooted.  I'll have to try it out again later.

**Comment by AnthonySlay** [comment]
I turned off Hot Reload and it seems to be working for me right now.  Changes to c# and xaml files are deployed while stopping and starting the debugger.  I tried this yesterday but it didn't seem to work.  So, you'll have to try it and see that it works for you.

From what I've read, this is a regression that is fixed with an IDE update.  This is also why the recent preview 11 was delayed in the windows vs2022 update.

**Comment by Phenek** [comment]
I still get this issue

**Comment by lhughey** [comment]
> I still get this issue, even with Xamarin.IOS 15.2.0.17
> 
> On iOS => The application has not been built. On Android => No Launchable Activity Found

I'm getting the same responses.

@AnthonySlay I'm glad you were able to find some resolution, however, turning off hotreload had no impact on my issues. I'm still not able to see compiled changes from c# or xaml

**Comment by talebi** [comment]
here same as @lhughey and @Phenek

**Comment by AnthonySlay** [comment]
Sorry all, turning off Hot Reload does not resolve the issue.  I was creating application after application trying to come up with steps to fix the issue without any luck.

A VS 2019 for Mac developer or MAUI maintainer will need to look into this issue.

**Comment by vniehues** [comment]
I'm currently facing the same issues and it is completely blocking my workflow. 
Did anyone find a workaround?

**Comment by Phenek** [comment]
Maybe it's because the project platefom is not really selectable as in Xamairin project?

Xamarin project on VS 2019:
![Screenshot 2022-01-20 at 19 08 19_censored](https://user-images.githubusercontent.com/4518686/150397150-496ac992-bc7b-4853-8dc6-0807c18d9d35.jpg)
MAUI project on VS 2022:
![Screenshot 2022-01-20 at 19 08 30](https://user-images.githubusercontent.com/4518686/150397171-555bfd50-47ee-4f3b-8809-29f4edc6cf01.png)

**Comment by vniehues** [comment]
Pre 12 fixed this problem for me

**Comment by lhughey** [comment]
@vniehues I updated my dotnet workflow and maui and I'm now able to deploy to my mac and see code changes reflected. I'm not able to deploy to my iOS sim still. Also, my VS 2022 Mac locks up immediately after attempting to deploy. I'm also getting the ole project.assets.json doesn't have a target for 'net6.0-ios'. I've already tried reinstalling VS. I guess no Maui for me.

**Comment by jfversluis** [comment]
Visual Studio for Mac does not have support for .NET MAUI at this time. Keep your eye on their releases for when it's there! For now you can run the apps through the command-line or use the Comet VS Code extension to make your life a bit easier :)
