### ISSUE TITLE
Invoke Platform Code Works For One Platform Only, But Flagged As Wrong For The Two Others

### ISSUE THREAD

**Issue by ctmobiledev** [dotnet/maui#5294]
### Description

First, a quick compliment to the entire .NET MAUI team! Having used Xamarin.Forms for several years, it's cool to see a new version with better structuring.

The issue I'm reporting here has to do with what Microsoft calls "invoking platform code", or (as I understand it) the replacement to the DependencyService object used in Xamarin.Forms. Simply put, the compiler appears to be fine with just one implementations of a base partial class, but not for the two others.

For a quick review of invoking platform code - and where I got the instructions to test - please see this page:

[](https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code)

This attached project demonstrates the nature of the issue. (The "bin" and "obj" folders were removed to reduce space.) It is based on the default project created when a new .NET MAUI one is selected.

[invoke-platform-bug-demo.zip](https://github.com/dotnet/maui/files/8250379/invoke-platform-bug-demo.zip)

In this package the following files are pertinent:

**DummyClass.cs, Shared/Root folder** - defines a namespace, a public partial class within that namespace, and a signature for a public partial method, DummyClassMethod().

**Platforms/Android/DummyClass.cs** - implementation of the method DummyClassMethod() with a single Debug.WriteLine statement indicating the Android platform is being called.

**Platforms/iOS/DummyClass.cs** - implementation of the method DummyClassMethod() with a single Debug.WriteLine statement indicating the iOS platform is being called.

**Platforms/Windows/DummyClass.cs** - implementation of the method DummyClassMethod() with a single Debug.WriteLine statement indicating the Windows platform is being called.

In two of the DummyClass.cs files, in the code editor, the compiler will flag the call to DummyClassMethod() with the following error message:

`"CS0757: A partial method may not have multiple implementing declarations."`

If I understand the Microsoft page above, then what I've coded should work. But in at least two cases, error CS0757 arises.

As I understand it, in order for this scheme to work, all of the following must be true:

- All files MUST refer to the same namespace.
- All classes MUST be public and use the same name, as well as marked "partial."

I've looked at one other blog and its information matches that of the Microsoft page, so I'm pretty sure my coding is correct. But if I missed something, I'd appreciate being apprised. 

### Steps to Reproduce

1. Create a new .NET MAUI project in Visual Studio.
2. In the shared project (root), create a new partial class under a new namespace. Add a signature for one partial method to the namespace without an implementation.
3. In each of the folders under their respective platforms - under "Platforms/" then the platform name - create a file of the same name, referencing the same namespace as in step 2, and the same partial class also, with a call to the partial method, but with an implementation of at least one executable line (e.g., a Debug.WriteLine statement). 
4. Look for the red squiggles under the method calls in at least two of the method calls for two of the platforms.

### Version with bug

Preview 13 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11, Windows 11, iOS uncertain

### Did you find any workaround?

The only workaround I'm tempted to use is to fall back to the DependencyService but I'd rather not do that. I'd like for this to be working. I'm attempting to learn the new platform.

**Comment by XamlTest** [comment]
Verified on Visual Studio Enterprise 2022 main 17.2.0 Preview 2.0 [32223.438.main]. Repro with above project.
**Platforms/Android/DummyClass.cs**

![image](https://user-images.githubusercontent.com/97647558/158317368-99f87109-9620-4783-8707-11f5ec86b7a7.png)

**Platforms/iOS/DummyClass.cs**

![image](https://user-images.githubusercontent.com/97647558/158317590-d756fefd-fa3e-4bd1-b315-59e4cb7452fc.png)

**Platforms/Windows/DummyClass.cs**

![image](https://user-images.githubusercontent.com/97647558/158317788-2751a5a6-7eb8-4e66-a8ae-36f26d877685.png)

**Comment by UweReisewitz** [comment]
Hi,
I thought the platform folders would have some sort of implicit "#if <Platform>" functionality for the whole source file.
But this is obviously not the case at the moment.
Wouldn't that solve this problem and also allow classes with the same name but different implementations in those folders?

**Comment by ctmobiledev** [comment]
Hello, Uwe:

I didn't think #if directives would be necessary. I thought the whole point of using .NET MAUI was that the whole process would be automated. Where's the benefit to developers if they're having to do pre-processor instructions manually?

In this original post from Microsoft:

https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/invoke-platform-code

it reads:

"Platform implementations should be placed in the correct Platforms child folders to ensure that the build system only attempts to build platform code when building for the specific platform. "

That would suggest that the compiler secludes code that's not applicable to a particular platform - that is, for an Android build, iOS and Windows code would be ignored.

If directives like #if are, indeed, required to use .NET MAUI that should be made very clear in the online documentation. Nothing I've seen so far suggests what you've mentioned.

Cordially,
Charles

________________________________

**Comment by UweReisewitz** [comment]
Hi Charles,
this was an issue in earlier previews but has been fixed in Preview 17.2.1 (that I have installed yesterday in the evening). 
It's now working as expected.

Best Regards
Uwe

**Comment by vankraster** [comment]
I have the same error.
@UweReisewitz  how you got the 17.2.1 Preview because I have 17.2.0 and it keep telling me is update
![Untitled](https://user-images.githubusercontent.com/27769564/160427995-bb4ec9b3-d088-4112-84cf-c7706823e209.png)
d

**Comment by UweReisewitz** [comment]
@vankraster no, I have the same version:
![image](https://user-images.githubusercontent.com/13447448/160429295-5ca24190-705b-4d6f-afa6-ac7c77d05937.png)

**Comment by genifycom** [comment]
I am using Microsoft Visual Studio Community 2022 (2) (64-bit) - Preview
Version 17.2.0 Preview 5.0
and I am still seeing this.

I created a default MAUI Blazor App with this version (and I do see the new Tizen specific Platform directory)

Just to be clear. The Error List shows the Error of "A partial method may not have multiple implementing declarations".
However, the Build output shows succeeded and the App will run (at least for Windows and Android).

But the Error showing in the Error List is very confusing.
