### ISSUE TITLE
Workloads fail to update after installing 2022 17.2 Preview 2

### ISSUE THREAD

**Issue by caseydierking** [dotnet/maui#5356]
### Description

I'm having issues getting a brand new .net maui blazor app to run in VS 2022 17.2 Preview 2. I had created the blazor app in VS 2022 (not preview) because it has the template for it.  I've tried running "dotnet workload install maui" but it gets confused because 6.0.300 is not found in the nuget feeds. I'm not sure how to resolve.

### Steps to Reproduce

1. Opened up a brand new .net Maui blazor application that was created from a .net maui template in VS 2022.
2. Attempted to run the project and get the following: 

```
Failed to update the advertising manifest microsoft.net.sdk.maccatalyst: microsoft.net.sdk.maccatalyst.manifest-6.0.300 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"..
Failed to update the advertising manifest microsoft.net.sdk.tvos: microsoft.net.sdk.tvos.manifest-6.0.300 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"..
Failed to update the advertising manifest microsoft.net.sdk.macos: microsoft.net.sdk.macos.manifest-6.0.300 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"..
Failed to update the advertising manifest microsoft.net.sdk.android: microsoft.net.sdk.android.manifest-6.0.300 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"..
Failed to update the advertising manifest microsoft.net.sdk.ios: microsoft.net.sdk.ios.manifest-6.0.300 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"..
Failed to update the advertising manifest microsoft.net.workload.mono.toolchain: microsoft.net.workload.mono.toolchain.manifest-6.0.300 is not found in NuGet feeds https://api.nuget.org/v3/index.json, C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\"..
Failed to update the advertising manife

```

### Version with bug

Preview 13 (current)

### Last version that worked well

Preview 12

### Affected platforms

Windows

### Affected platform versions

Every platform

### Did you find any workaround?

Not yet.

**Comment by eslamo** [comment]
Same issue here

**Comment by jfversluis** [comment]
What happens if you create a new app from the VS 2022 preview? Does that work?

You shouldn't need to install workloads manually through the CLI. Additionally, I don't know what templates are in the non-preview VS2022, but those shouldn't be there and probably not be used.

**Comment by caseydierking** [comment]
@jfversluis 

I installed the templates on VS 2022 Preview using dotnet new -i Microsoft.Maui.Templates
Then, I created a new Maui Blazor Application. 

I only have Windows Machine available to target. When I run the project, I get the errors below:
![image](https://user-images.githubusercontent.com/3005311/158818146-401bdf8e-8f67-46b9-994f-b2405af84096.png)


```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1147	To build this project, the following workloads must be installed: maui-ios
To install these workloads, run the following command: dotnet workload install maui-ios	Blazor.Maui	C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	
Error	NETSDK1147	To build this project, the following workloads must be installed: maui-windows
To install these workloads, run the following command: dotnet workload install maui-windows	Blazor.Maui	C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	
Error	NETSDK1147	To build this project, the following workloads must be installed: maui-maccatalyst
To install these workloads, run the following command: dotnet workload install maui-maccatalyst	Blazor.Maui	C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	
Error	NETSDK1147	To build this project, the following workloads must be installed: maui-android
To install these workloads, run the following command: dotnet workload install maui-android	Blazor.Maui	C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets	38	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	Blazor.Maui	C:\Users\Casey Dierking\Desktop\EyerollApp\Blazor.Maui\Blazor.Maui\Blazor.Maui.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	Blazor.Maui	C:\Users\Casey Dierking\Desktop\EyerollApp\Blazor.Maui\Blazor.Maui\Blazor.Maui.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	Blazor.Maui	C:\Users\Casey Dierking\Desktop\EyerollApp\Blazor.Maui\Blazor.Maui\Blazor.Maui.csproj	1	
Error	NU1012	Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst	Blazor.Maui	C:\Users\Casey Dierking\Desktop\EyerollApp\Blazor.Maui\Blazor.Maui\Blazor.Maui.csproj	1	
Warning (active)	RZ10012	Found markup element with unexpected name 'SurveyPrompt'. If this is intended to be a component, add a @using directive for its namespace.		c:\Users\Casey Dierking\Desktop\EyerollApp\Blazor.Maui\Blazor.Maui\Pages\Index.razor	7	
```

**Comment by jfversluis** [comment]
Looks like something didn't get installed right because it says that you have none of the workloads installed. Did you click the .NET MAUI workload during the setup? Also, did you upgrade your preview version or reinstalled as recommend?

**Comment by caseydierking** [comment]
I tried to follow the guide as recommended.

 I uninstalled the .net 6 SDK preview and uninstalled VS2022 Preview. I then installed VS2022 Preview from the VS Installer with the Mobile Development with .NET checked. 
![image](https://user-images.githubusercontent.com/3005311/158820612-ee18a21b-e1df-4b77-ad9f-feb23ce2fa78.png)

Perhaps I missed a step there?

**Comment by jfversluis** [comment]
Hm nope that should be good :) maybe if you try repair installation?

If all else fails you could try the instructions here: https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md#net-maui-workload

Use the preview 14 ones. Hopefully that should fix it, although I'm curious why it doesn't work with the installer

**Comment by caseydierking** [comment]
Fantastic! That did the trick. I am too not sure why it didnt download with the installer but this was brilliant. Thank you!

**Comment by jfversluis** [comment]
Glad we unblocked you for now at least. I'm pretty sure this is on our radar and should be a problem by the time we get to GA. I'm closing this one for now, but be sure to let me know if this happens again for a next version and I'll explore a bit harder :)

Thanks and happy developing!

**Comment by KiruyaMomochi** [comment]
It happened to me.
Using VS 2022 Preview 2.1. Have also tried `repair` option of installer. Still fails to build.

```
Build started...
1>------ Build started: Project: MauiApp1, Configuration: Debug Any CPU ------
Failed to restore C:\Users\xtyzw\Projects\AssetStudioMaui\MauiApp3\MauiApp3.csproj (in 11 ms).
Failed to restore C:\Users\xtyzw\Projects\AssetStudioMaui\MauiApp2\MauiApp2.csproj (in 10 ms).
Failed to restore C:\Users\xtyzw\Projects\AssetStudioMaui\MauiApp1\MauiApp1.csproj (in 14 ms).
NuGet package restore failed. Please see Error List window for detailed warnings and errors.
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To build this project, the following workloads must be installed: maui-android
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-android
1>Done building project "MauiApp1.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To build this project, the following workloads must be installed: maui-windows
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-windows
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To build this project, the following workloads must be installed: maui-maccatalyst
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-maccatalyst
1>Done building project "MauiApp1.csproj" -- FAILED.
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To build this project, the following workloads must be installed: maui-ios
1>C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): 
    error NETSDK1147: To install these workloads, run the following command: dotnet workload install maui-ios
1>Done building project "MauiApp1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

<details>
<summary>
VS 2022 Version 17.2.0 Preview 2.1
</summary>

```
Microsoft Visual Studio Community 2022
Version 17.2.0 Preview 2.1
VisualStudio.17.Preview/17.2.0-pre.2.1+32317.152
Microsoft .NET Framework
Version 4.8.09022

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA430
Microsoft Visual C++ 2022

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   17.2.240.24236
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.240.24236
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.2.240.24236
Azure Functions and Web Jobs Tools

C# Tools   4.2.0-2.22159.10+f3a5bad242b7a7b8149ae644de0a61c2f1bffc8d
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.32314
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Mono Debugging for Visual Studio   17.1.10 (65f98f5)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2215202+658e2db05d0daa9326356ee1edc85cd3d1b970c4
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62203.01080
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.10302.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-2.22159.10+f3a5bad242b7a7b8149ae644de0a61c2f1bffc8d
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.32314
Visual C++ for Linux Development

Visual F# Tools   17.1.0-beta.22108.1+63bcc94efda4fe19b612b167a25fdbcee796040b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.2.0.85 (d17-2-p2@c900809)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.2.0.64 (remotes/origin/main@3d19e6caf)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.1.13 (bb31b34)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   12.2.99.130 (main/e89ae42)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: f34bd77
    Java.Interop: xamarin/java.interop/main@aae23c97
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.38.0@ccd83d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@f0b3abd


Xamarin.iOS and Xamarin.Mac SDK   15.7.0.410 (478c1d2c8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

</details>

**Comment by daghb** [comment]
Can confirm this is also a problem with 17.2.0/Preview 3.0
