### ISSUE TITLE
No Maui Project Template and error: Platform version is not present for one or more target frameworks

### ISSUE THREAD

**Issue by ConnorJBrown** [dotnet/maui#5778]
### Description

I seem to have messed up my MAUI installation on Windows VS2022 17.2.0 Preview 2.1.

I cannot see the MAUI template when creating a new project.

When opening an existing MAUI project I see the following error:
`Platform version is not present for one or more target frameworks, even though they have specified a platform: net6.0-android, net6.0-ios, net6.0-maccatalyst`

Running `dotnet workload list` gives me the following:
```
>dotnet workload list

Installed Workload Ids      Installation Source
-----------------------------------------------
maui-windows                VS 17.2.32317.152
maui-maccatalyst            VS 17.2.32317.152
maccatalyst                 VS 17.2.32317.152
maui-ios                    VS 17.2.32317.152
ios                         VS 17.2.32317.152
maui-android                VS 17.2.32317.152
android                     VS 17.2.32317.152
```

Repairing my VS2022 installation did not fix this, and uninstalling & reinstalling did not fix this either.

Opening the same projects on a different computer with the same VS2022 version works fine

### Steps to Reproduce

This issue happens consistently for me but I cannot reproduce it on a different machine.

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

net6.0-windows10.0.19041;net6.0-android;net6.0-ios;net6.0-maccatalyst

**Comment by jfversluis** [comment]
While it shouldn't be necessary, you can install the templates manually with `dotnet new -i Microsoft.Maui.Templates` that will also make them show up in VS. Going to trust this fixes it, if not feel free to tag me :) thanks!

**Comment by jfversluis** [comment]
Interestingly enough just `maui` is not part of the list. What happens if you manually run `dotnet workload install maui`?

**Comment by jfversluis** [comment]
I'm getting another report for something similar like this so there might be something here. Let's reopen for now.

**Comment by jfversluis** [comment]
As per the instructions [here](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md). Would you be able to try and run this?

`iwr https://aka.ms/dotnet/maui/maui-install.ps1 -OutFile maui-install.ps1;
.\maui-install.ps1 -b 'release/6.0.2xx-preview14' -v '6.0.200-preview'`

Of course you're welcome to inspect the contents of the script first if you don't just trust us :)

**Comment by ConnorJBrown** [comment]
@jfversluis 
```
Installation rollback failed: One or more errors occurred. (microsoft.netcore.app.runtime.mono.android-arm.msi.x64::6.0.3 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-3ba4b3f4/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0-1/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json".)
Workload installation failed: One or more errors occurred. (microsoft.netcore.app.runtime.mono.android-arm.msi.x64::6.0.3 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-3ba4b3f4/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0-1/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json".)
```

Here is the full log
[MAUI5778Log.txt](https://github.com/dotnet/maui/files/8418497/MAUI5778Log.txt)

**Comment by evandigby** [comment]
I am having this same issue. I would attach my logs but they are virtually identical to those of @ConnorJBrown 

Please let me know if there's anything I can do to help!

**Comment by evandigby** [comment]
After a bit of work and searching, I was able to work around this issue using the following (run from my solution root directory in an admin powershell):

```powershell
dotnet new globaljson --sdk-version 6.0.200
iwr https://aka.ms/dotnet/maui/maui-install.ps1 -OutFile maui-install.ps1; .\maui-install.ps1 -b 'release/6.0.2xx-preview14' -v '6.0.200'
```

This assumes you have dotnet SDK 6.0.200 installed. Hopefully it helps you too @ConnorJBrown

**Comment by nukedbit** [comment]
> 

I'm also expierencing this issue, but it happened after i have uninstalled vs preview an since rienstall i can''t build maui projects anymore.

I also tried  your scripts, but it fail with the following errors.



```
....

Removing Microsoft.Android.Runtime.32.android-x64.31.0.200.109.msi .... Done
Removing Microsoft.Android.Templates.31.0.200.109-x64.msi .... Done
Downloading Microsoft.NETCore.App.Runtime.Mono.android-arm.Msi.x64 (6.0.3)
Installation rollback failed: One or more errors occurred. (microsoft.netcore.app.runtime.mono.android-arm.msi.x64::6.0.3 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-3ba4b3f4/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0-1/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json".)
Workload installation failed: One or more errors occurred. (microsoft.netcore.app.runtime.mono.android-arm.msi.x64::6.0.3 is not found in NuGet feeds https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-3ba4b3f4/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0-1/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-ee0a97a0/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaCleaning up...

```

These are the SDK i have installed


```3.1.417 [C:\Program Files\dotnet\sdk]
5.0.212 [C:\Program Files\dotnet\sdk]
6.0.200 [C:\Program Files\dotnet\sdk]
6.0.300-preview.22154.4 [C:\Program Files\dotnet\sdk]```

**Comment by v-longmin** [comment]
Verified the issue on 17.2.0 Preview 2.1 [32317.152.main], it's not repro.

**Comment by nukedbit** [comment]
Updating to RC1 fixes new projects.
But for some reasons :
1) i had to reset all visual studio settings.
2) delete all .vs folders
3) delete all .user folder

Without deleting those files, Local Packages folder was not listed inside VS, after cleanup maui is working for existing projects i have running locally.

**Comment by jfversluis** [comment]
Thanks for being on top of this @nukedbit ! More people seeing this is resolved with the latest release?

**Comment by maxkoshevoi** [comment]
Can confirm that adding `global.json` with `net6` to solution's root fixes it (I also have net7-preview installed, and it seems like it messes maui up)

My `global.json`:
```
{
  "sdk": {
    "version": "6.0.300-preview.22204.3"
  }
}
```

PS: Latest preview didn't fix it, I still need `global.json`

**Comment by ConnorJBrown** [comment]
Installing 6.0.300 RC1 using instructions from [here](https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md) fixes this issue for me

**Comment by dylanberry** [comment]
I ran into this as well after installing .NET 7 and can confirm that the fixes offered by @evandigby and @maxkoshevoi work.

```pwsh
cd SolutionRoot
dotnet new globaljson --sdk-version 6.0.300-preview.22204.3
```

**Comment by jfversluis** [comment]
Thanks everyone for letting us know! Seems like not having .NET 7 or adding a `global.json` does the trick in this case!
