### ISSUE TITLE
Binding an Item's height and width to another item's height and Width in XAML causes exceptions and unexpected behaviors 

### ISSUE THREAD

**Issue by DamienDoumer** [dotnet/maui#6200]
### Description

Every time I try binding a view's height or width to another view's height or width in XAML,
 I get an exception, stating `System.InvalidOperationException: 'Width cannot be less than zero.'`
After getting this exception, I did a value converter to make the value I bind to be always greater than 0, but The value of the referenced view's sizes always keeps increasing forever. 

### Steps to Reproduce

I reproduced both bugs in two pages I set here in this repository. https://github.com/DamienDoumer/MAUIBugs/tree/master/MAUIBugs/ViewSizeReferenceBug 

### Version with bug

Release Candidate 1 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

All

### Relevant log output

```shell
**System.InvalidOperationException:** 'Width cannot be less than zero.'
```

**Comment by kristinx0211** [comment]
verified repro on android 11 with above project.

**Comment by hartez** [comment]
There's a _chance_ this was fixed by #6323 (or at least that the exception portion of it was fixed).

**Comment by XamlTest** [comment]
Verified this on Visual Studio Enterprise 17.6.0 Preview 4.0. 
The first issue: Exception "System.InvalidOperationException: 'Width cannot be less than zero.'" does not reproduce on Android emulator (13.0-API 33).
The second issue: "The value of the referenced view's sizes always keeps increasing forever" still reproduce on Android emulator (13.0-API 33).
[6200.zip](https://github.com/dotnet/maui/files/11285006/6200.zip)
