### ISSUE TITLE
ImageSource is not work when set Image.Source to file in external storage

### ISSUE THREAD

**Issue by jevonsflash** [dotnet/maui#6525]
### Description

When I load an Android External Storage Image using the  Image.Source  binding ImageSrouce.
 Image is not displayed .

### Steps to Reproduce

I want to read this image:"/storage/emulated/0/Documents/albumart9100466824972896645.jpg" and show it, I assign AlbumArt to my binding object as follows  
 `AlbumArt = ImageSource.FromStream(() =>
            {
               var b = File.ReadAllBytes("/storage/emulated/0/Documents/albumart9100466824972896645.jpg");
               return new MemoryStream(b);
            });`

`AlbumArt = ImageSource.FromFile("/storage/emulated/0/Documents/albumart9100466824972896645.jpg");`

the image has been readed exactly correct:
![image](https://user-images.githubusercontent.com/11273359/165431391-cd4a7f7b-ab69-4e88-8117-54fd8f847205.png)
![image](https://user-images.githubusercontent.com/11273359/165432975-4ebe1b12-43d9-467b-9923-f2ff2831527c.png)

I tried using ImageSource.FromStream, and  using ImageSource.FromFile, it didn't work  (no display, Image control is blank)

 
The only thing it is work is to use Resources/albumart_placeholder. JPG  which is set to MauiImage
`AlbumArt = "albumart_placeholder"; //it is work` 

### Version with bug

Preview 14

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by jfversluis** [comment]
You mention preview 14, did you try RC2 yet? I know there have been some changes in the image area

**Comment by VincentBu** [comment]
I'm using 17.3.0 Preview 1.0 and `Image.Source = ImageSource.FromFile(imagePath)` also doesn't work for me.

**Comment by jevonsflash** [comment]
> You mention preview 14, did you try RC2 yet? I know there have been some changes in the image area

I have update to latest vs 2022 17.2.0 Preview 5.0,  and confirm that the problem still exists.

**Comment by jevonsflash** [comment]
How to check maui version? my maui-check tool can't connect to their server.  All I see is the version of Xamarin in About window of visual studio,  the Xamarin version is 17.2.0.169

**Comment by Symbai** [comment]
Its still bugged and it also happens on iOS.

**Comment by NJCCJohnWatson** [comment]
是孙燕姿欸！
I think its better way is read by stream and bind to image

**Comment by Symbai** [comment]
> I think its better way is read by stream and bind to image

Which is also still bugged in Android and iOS #7074 its currently not possible to load any external images. Whether its from file, stream or web.

**Comment by NJCCJohnWatson** [comment]
Because the MAUI File api still have bugs,and the developer tell us use FilePicker to get **external storage** file
And the file will not can be read directly(could caused by Android control) .
 it will be save a **virual path** on /data/0/**[your package name]** /cache/xxx/xxx/**[yourimagename]**.
In Android devices you use blow code to get image and set it to <Image/> tag on xaml.

1.First we need a async FilePicker 
```
public async Task<string> TakePath()
        {
            if (MediaPicker.Default.IsCaptureSupported)
            {
                FileResult photo = await MediaPicker.Default.PickPhotoAsync();

                if (photo != null)
                {
                    // save the file into local storage
                    return photo.FullPath;
                }
                else
                {
                    return "";
                }
            }
            else
            {
                return "";

            }
        }    
```    
2.Then use a event to mount FilePicker
```
    private async void SetDownloadPath(object sender, EventArgs e)
    {
        FileIO fs = new FileIO();
        string path = await fs.TakePath();
        CounterLabel.Text = path;
        //get parent folder path
        FileInfo fi = new FileInfo(path);
        var realPath = fi.Directory;
        savingPath = path;
    }
```

3.Now we get the picture path,use blow function to set to Image
```

    private void LoadImageLocal(string path, Image img)
    {        
        var byteArray = File.ReadAllBytes(path);
        img.Source = ImageSource.FromStream(() => new MemoryStream(byteArray));
        //both can use, just for test
        img = new Image
        {
            Source = ImageSource.FromFile(path)
        };
    }
```
4.Load image from web , its more easiler too

```
    private void LoadImageUrl(string url, Image img)
    {
        var byteArray = new HttpClient().GetByteArrayAsync(url).Result;
        img.Source = ImageSource.FromStream(() => new MemoryStream(byteArray));
    }
```
Now we fixed **Read** issue and my problem is can not be **Write** to External Storage 
Only can write file in  /data/0/**[your package name]** /file/ 
It's so conveniently!🤣

All code above from my practicing project https://github.com/NJCCJohnWatson/BiliAvatarMAUI
And about further content of Filepicker on MSDoc: https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/storage/file-picker?tabs=android

**Comment by homeyf** [comment]
Verified this issue with Visual Studio Enterprise 17.8.0 Preview 2.0. Can repro on Windows platform with sample project.
https://github.com/NJCCJohnWatson/BiliAvatarMAUI
![image](https://github.com/dotnet/maui/assets/82450723/b50abc87-54e1-462f-9136-a40d42598323)

**Comment by Mimisss** [comment]
This still is a problem on Android. Binding either a file path or an ImageSource to Image.Source does NOT show anything. 

It is working on Windows, though. Let's say you are capturing photos using  e.g. ZXing.Net.Maui.Controls.CameraView and saving them to a temp directory:

```
var capture = await cameraView.CaptureAsync();
if (capture != null)
{
    var filePath = Path.Combine(FileSystem.CacheDirectory, Path.GetRandomFileName());
    using (var fileStream = File.Create(filePath))
    {
        await capture.CopyToAsync(fileStream);
    }
    viewModel.Photo = filePath;
}
```

Then, binding Source to viewModel.Photo works (on Windows only):

```
<Image Source="{Binding Photo}" />
```

@jevonsflash you mentioned:

> The only thing it is work is to use Resources/albumart_placeholder. JPG which is set to MauiImage
> AlbumArt = "albumart_placeholder"; //it is work

Can you please explain with an example? Can I save image files in Resources at runtime and then successfully bind them to Image control?

**Comment by jfversluis** [comment]
Looks like the linked SO question and everything else talks about .NET 8 at the most. Can someone verify this is still an issue with .NET 9?

**Comment by Mimisss** [comment]
I have to say that the _actual_ problem **in my case** was caused by the `ZXing.Net.Maui.Controls.CameraView` control; the `Source` property of the `Image` control works as expected as long as a proper value is assigned to it. A very nice way to make it work is by using an extension method like this:

```
public static ImageSource? Refresh(this string path)
{
    if (!string.IsNullOrEmpty(path) && File.Exists(path))
    {
        return ImageSource.FromStream(() => new MemoryStream(File.ReadAllBytes(path)));
    }
    else return null;
}
```

So, you can load an image by writting:

```
MyImage.Source = path.Refresh();
```

where `path` is the absolute path to the image file.

The above was part of the answer to the SO question I've linked to in my previous post. So, please don't take my previous post into account; the `Image` control was not showing anything as a side-effect of using the `ZXing.Net.Maui.Control.CameraView` control. When I started using `MediaPicker` everything worked properly.

> This still is a problem **on Android**. Binding either a file path or an ImageSource to Image.Source does NOT show anything if the file is on external storage (i.e. not a Resource).
> 
> It works on Windows, though.
> 
> [Here's a related SO question](https://stackoverflow.com/questions/79424675/how-to-bind-image-file-created-in-cache-directory-to-net-maui-image-control-on)
> 
> How can this still be an open issue? 🤒
> 
> Is there a workaround? How do developers load images from external storage to .NET MAUI Image?

**Comment by bhavanesh2001** [comment]
Whenever you try to read a file from external storage, you should always consider the restrictions imposed by the operating system. To read an image on Android, you need to have `READ_EXTERNAL_STORAGE` permission for Android 12 and below or `READ_MEDIA_IMAGES` permission for Android 13 and above.

I created a demo to illustrate this with .NET9 latest release(9.0.40) . I'm loading images something like this

```c#
fileImage.Source = ImageSource.FromFile("/storage/emulated/0/MyFolder/dotnet.png");
streamImage.Source = ImageSource.FromStream(() => new MemoryStream(File.ReadAllBytes("/storage/emulated/0/MyFolder/dotnet.png")));
```

**On Android 12(API 31)**


https://github.com/user-attachments/assets/a378ec33-e0e7-472b-9bda-1615b22c85fc

**On Android 15(API 35)**

https://github.com/user-attachments/assets/ac18afe4-076b-4b0a-ba6f-3ac031e58fa3

@jfversluis I don't think this is a bug

**Comment by jfversluis** [comment]
I see what you're saying and I agree. Depending on the scenario it doesn't seem like a smart thing to do to load images from external storage. Also, I think Android changed some things in this regard now too. If these are images that the user is picking or otherwise has to choose then yes. If these are images that you just need for your app to function that this seems like a bad idea since you will need to require the users permission and they might find it strange.

Thanks for the investigation here @bhavanesh2001!

If someone thinks there is still an issue here, please open something new with a clear explanation of why you think that is and a reproduction. Thanks!
