### ISSUE TITLE
With UseMaui = true in class library I get a '"CopyLocalFilesOutputGroup" does not exist' error

### ISSUE THREAD

**Issue by pauldendulk** [dotnet/maui#6529]
### Description

When I create a class library for reusable maui components and add ```<UseMaui>true</UseMaui>``` to the csproj I get this error: 
```C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets``` 

Used rc2 and VS preview 5

I am not sure if I am supposed to use ```<UseMaui>true</UseMaui>``` for this purpose. I would like to know the alternative way if there is one. Still there may have to be a better error in this situation.

Screenshot of the situation:
![image](https://user-images.githubusercontent.com/963462/165458258-91fa12e2-f771-4744-ba89-b40bf72e3585.png)

Minimal reproduction:
[CopyLocalFilesOutputGroup-does-not-exist.zip](https://github.com/dotnet/maui/files/8569575/CopyLocalFilesOutputGroup-does-not-exist.zip)

### Steps to Reproduce

1. Create a new maui app
2. Create a new class library
3. Add <UseMaui>true</UseMaui> to the csproj of the class library
4. Add a reference to the class library in the maui app
5. Compile.

### Version with bug

Release Candidate 2

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

It is a compile problem so I guess it affects all platforms with RC 2. I compiled on Windows.

### Did you find any workaround?

No

### Relevant log output

```shell
Build started...
1>------ Build started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
1>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
1>ClassLibrary1 -> C:\Users\pauld\source\repos\MauiApp3\ClassLibrary1\bin\Debug\net6.0\ClassLibrary1.dll
2>------ Build started: Project: MauiApp3, Configuration: Debug Any CPU ------
2>Skipping analyzers to speed up the build. You can execute 'Build' or 'Rebuild' command to run analyzers.
2>MauiApp3 -> C:\Users\pauld\source\repos\MauiApp3\MauiApp3\bin\Debug\net6.0-windows10.0.19041.0\win10-x64\MauiApp3.dll
2>C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets
2>Done building project "ClassLibrary1.csproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

**Comment by v-longmin** [comment]
Verified not repro on windows as below screenshot.
![image](https://user-images.githubusercontent.com/40230425/165461902-40bf9ee4-c423-4e22-9407-145b5473b531.png)

**Comment by XamlTest** [comment]
Verified this issue with Visual Studio Enterprise 17.3.0 Preview 1.0 [32414.199.main]. Repro on Windows with above project.

**Comment by UweReisewitz** [comment]
My project has the same problem but does not use the CommunityToolkit. Is there a workaround known?

Thanks in advance

**Comment by UweReisewitz** [comment]
After I made sure, that ALL MAUI-csproj files had the current settings AND cleaned the solution, the problem went away.

I used the following text:
        <TargetFrameworks>net6.0;net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>
        
        

and

        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
        <TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
        <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>

I did not rouch the rest of the csproj files. Please do not forget to clean the solution.

**Comment by UweReisewitz** [comment]
This does not work if you have a class library that uses only 
`<UseMaui>true</UseMaui>`
(no platform specific code) and is referenced by a Maui application. The building of the library then fails with

`C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.
`

Repro steps:

- Create a Maui Application. 
- Add a Maui class library
- Reference the class library from the application
- Modify the csproj of the class library as follows:

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0</TargetFrameworks>
		<UseMaui>true</UseMaui>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

</Project>

```
Build the project. The build of the library will fail with the above error but **only** if it is referenced from the main project. If it is not referenced the build succeeds.

**Comment by ChristopherMWood** [comment]
Can confirm I am seeing the same thing. I'm working on a Nuget package for Maui and I usually test locally by referencing projects, but am getting build errors as described above.

**Comment by mattleibow** [comment]
Try adding <SingleProject>true

I think some defaults are only set when that is set to true as we don't want to start changing things.

However, maybe it should so I will use this issue to try and reduce this unexpectedness.

I am afk right now, but you can see the 3 props that is set in the SingleProject.props file, the experimental msix, library layout and then another I think.

**Comment by mattleibow** [comment]
I edited my comment as it appears that GitHub took my mobile comment with angle brackets as literal html and removed it.

You need to set SingleProject=true

**Comment by KlaasTroost** [comment]
At this moment I use:

		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>

these settings in my Windows project. But still no succes, I am getting a little frustrated now. Everything worked till de Release Candidates.

When RC1 was released I had some problems but I fixed them. But since RC2 (when you think it should getting better) the project can not be build.

**Comment by UweReisewitz** [comment]
I can confirm that setting SingleProject=true in both projects (App and Library) does not solve the problem here.

**Comment by shugaoye** [comment]
I have the same problem after upgraded to RC2. However, I resolved this issue after I changed the project file using RC2 project template as below. Please give it a try.

```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

</Project>

```

**Comment by UweReisewitz** [comment]
Yes, that solves the problem for "normal" MAUI projects. It does not help if you have a project that uses MAUI but no platform specific code. Then the problem persists (see comments above)

**Comment by genifycom** [comment]
I created all of my MAUI libs from scratch with RC2 and copied the class files over. The CSPROJ is as per [shugaoye](https://github.com/shugaoye) post. However. I cannot build the main project (i.e. that references the 5 MAUI libraries).

C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.2.5513\Sdk\WinUI.NetCore.targets

This happens for two of my 5 MAUI Libs. If I compile them only, then the compile succeeds.

Currently dead in the water. :(

**Comment by mattleibow** [comment]
I believe this is an issue with the Windows App SDK that assumes that the class libraries have the same windows TargetFramework as the app project. It doesn't do a compatible check. 

If the app is net6.0-windows10.0.19041.0, then that tfm must exist exactly in the class library.

It even matters with the last .0 in the version as the app just says get the bits using my tfm.

I think the solution would be to also add the windows tfm to the class library.

I'll be trying to repro this on a Windows only project and log an issue with them.

**Comment by UweReisewitz** [comment]
Thanks for the input. But why did this work before RC2?

**Comment by mattleibow** [comment]
I have been digging some more and there are a few issues that all come together. So the real issue why it is broken is still the fact that the WinUI targets assume the TFM is exactly the same.

However, the one difference before is that the targets used to be located in the WindowsAppSDK nuget, so when the app called a specific target in the library that was NOT winui, it actually fell through to a dummy target. However, due to a few bugs in certain situations, we moved some of the targets from the nuget into MAUI temporarily. This fixes a few issues with resources and packaging, but exposed this issue.

We have a condition now in the targets that was checking if the library was a maui app and a windows TFM, however, because the app lies to us and tells us we are a windows library, it starts down the wrong path.

I have a PR that should make things much better: #6767

But, the current workaround is to make sure you have the windows TFM and then you might also have to set `EnablePreviewMsixTooling=True` and `GenerateLibraryLayout=True`.

**Comment by KlaasTroost** [comment]
@mattleibow  thank you very much. I added "TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>" in my .net6-0 class library projects and now Also added the GenerateLibraryLayout to the project files and now the Windows app gets compiled.  

But the app is still not running, I keep you posted.

**Comment by sailman342** [comment]
I had the same problem. 

I Started with a single project then I decided to split it into project and library. 

It took me some time but close to end I was stuck with the same message ...

The problem was that when the library was created it automatically used

$(TargetFrameworks);net6.0-windows10.0.19041.0

while the project was using

$(TargetFrameworks);net6.0-windows10.0.19041

Deleted the    .0    then it build and worked fine :-)

Hope it helps :-)

**Comment by KlaasTroost** [comment]
That did not work for me.

**Comment by sailman342** [comment]
Library then project :

```
	<PropertyGroup>
		<TargetFrameworks>net6.0;net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">14.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>
```
```

	<PropertyGroup>
		<TargetFrameworks>net6.0-android;net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows')) and '$(MSBuildRuntimeType)' == 'Full'">$(TargetFrameworks);net6.0-windows10.0.19041</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>ZClubMaui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>ZClubMaui</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.zclubmaui</ApplicationId>
		<ApplicationId Condition="$(TargetFramework.Contains('-windows'))">836C759D-493F-4806-8F0D-0C174084DFD6</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-ios'">12.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-maccatalyst'">14.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="'$(TargetFramework)' == 'net6.0-android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$(TargetFramework.Contains('-windows'))">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>
```

**Comment by KlaasTroost** [comment]
After some investigation I saw this error in the Event Viewer:

Application: <AppName>exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException: Unable to load DLL 'Microsoft.ui.xaml.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at DigiD.Desktop.Maui.WinUI.Program.XamlCheckProcessRequirements()
   at DigiD.Desktop.Maui.WinUI.Program.Main(String[] args)

Does anyone recognize this error?

**Comment by sailman342** [comment]
No it works fine for me now. The problem I face is that on Mac OS Visual Studio I can only buils with libraries if all of the MAUI type, impossible to build with a pure .Net 6 library :-(

**Comment by KlaasTroost** [comment]
It WORKS!!! I made a mistake with a compiler directive so the following lines did not get compiled:

```c#
        builder.ConfigureEffects(effects =>
        {
            effects.AddCompatibilityEffects(AppDomain.CurrentDomain.GetAssemblies());
        });
 ```
Still a problem with handling errors if an effect can not be found . There was no indication what so ever that pointed to the not existing effects.

**Comment by mattleibow** [comment]
Yeah. :( Windows errors are crazy hard to debug. Usually when this happens I check the C++ and CLR check boxes in the Exception Settings window - not perfect, but catches more exceptions (be warned WinUI throws a bit but you have to continue through as they are caught elsewhere):

![image](https://user-images.githubusercontent.com/1096616/166874637-ede054d8-67c9-4bab-b888-e2a67da3ade3.png)

**Comment by pauldendulk** [comment]
@mattleibow The associated PR was merged to main six days ago. Yesterday RC.3 was released. I ran 'dotnet workload install maui macos android ios maccatalyst' but the attached solution still results in the same error. 

Also, I don't see the PR mentioned in the release notes. Is it not expected to be part of RC.3? If not when can we expect it? How can I monitor its release?

**Comment by mattleibow** [comment]
Can you attach/send me a binlog? I am seeing a bunch of issues being reported but I can't reproduce it.

**Comment by UweReisewitz** [comment]
Just a (very) wild guess here: 
I have the same problem with compiling a Nuget package but the maintainer is unable to reproduce it (even on Preview 6). Could there be a problem on Non-English Windows? 
I'm using VS2022 with the english UI on a German Windows. I haven't updated to 17.3 yet because the update server are not responding.

**Comment by sailman342** [comment]
Hi Paul, why you don't create directly a MAUI Library instead, rather than editing the csproject to set MAUI to true ? It workd for me ....

**Comment by pauldendulk** [comment]
> Can you attach/send me a binlog? I am seeing a bunch of issues being reported but I can't reproduce it.

Below is the binlog of this command:
```dotnet build -bl:C:\logs\msbuild.binlog MauiApp3.sln```. 
Ran on the project attached in the original post.

[MauiApp3.binlog.zip](https://github.com/dotnet/maui/files/8670827/MauiApp3.binlog.zip)

btw, I could not update Visual Studio Preview to it's new version because 'checking for updates' keeps spinning (but I did update the workloads).

Also it is crucial to select 'Windows Machine'  in visual studio. If I select Android it succeeds.

**Comment by pauldendulk** [comment]
> Hi Paul, why you don't create directly a MAUI Library instead, rather than editing the csproject to set MAUI to true ? It worked for me ....

Thanks @sailman342 , that way it does indeed compile. The reason I did not do this before is that I was working with an existing project that did compile correctly before. Even though I think it is good to have a proper understanding of what is going on in the situation reported.

**Comment by UweReisewitz** [comment]
@mattleibow I can confirm that the problem is still present for a Windows Build on my machine.

VS 2022 17.3 Preview 1.0 (english UI)
Windows 11 Enterprise 21H2 (22000.675) (german UI)

**Comment by mattleibow** [comment]
Hmmm

Is there a difference in the csproj between the one that works and the one that does not?

Did you define the `<SingleProject>true` as well?

**Comment by UweReisewitz** [comment]
Maybe this has slipped away. The problem happens under following circumstances:

- **Multi** Platform Executable; MAUI; Building for **Windows**
- **Single** Platform Library; MAUI:
```
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>Prism</RootNamespace>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <UseMaui>true</UseMaui>
    <ImplicitUsings>true</ImplicitUsings>
  </PropertyGroup>

```
Then the problem is reported for each of the libraries that have only the net6.0 target

**Comment by mattleibow** [comment]
Does this happen in the IDE or when building on the command line?

**Comment by UweReisewitz** [comment]
I'm building in the IDE

**Comment by mattjohnsonpint** [comment]
I think this should be re-opened.  I got the same error building in GitHub Actions.

https://github.com/getsentry/sentry-dotnet/runs/6530062417?check_suite_focus=true#step:9:217

> C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.3.5667\Sdk\WinUI.NetCore.targets(188,5): error MSB4057: The target "CopyLocalFilesOutputGroup" does not exist in the project.  C:\Program Files\dotnet\packs\Microsoft.Maui.Sdk\6.0.300-rc.3.5667\Sdk\WinUI.NetCore.targets [D:\a\sentry-dotnet\sentry-dotnet\src\Sentry.Maui\Sentry.Maui.csproj]

This is on a class library that has:

```xml
    <TargetFramework>net6.0</TargetFramework>
    <UseMauiCore>true</UseMauiCore>
```

It is intended to be used by applications targeting MAUI on any platform.  Is there a better way to set that up?

**Comment by mattjohnsonpint** [comment]
A little more experimentation on a Windows box, and I've found that the error only occurs when both of the following are true:

- The MAUI app references a MAUI class library (a class library that has `<UseMaui>` or `<UseMauiCore>`)
- The MAUI app uses `<TargetFrameworks>` instead of `<TargetFramework>`

It does not seem to matter whether the class library is targeting one or more platforms, or which platform it is.  It also doesn't seem to matter whether the app is targeting Windows or Android or something else - but the build error only occurs when building on Windows.

**Comment by UweReisewitz** [comment]
On my machine this also happens with `<TargetFramework>`

**Comment by pauldendulk** [comment]
I think the fix has simply not in the rc.3 released. As I [posted](https://github.com/dotnet/maui/pull/6767#issuecomment-1126950470) in the MR thread:

> The rd.3 release tag is set 12 days ago:
> https://github.com/dotnet/maui/tags
> While the MR was merged 10 days ago.
> https://github.com/dotnet/maui/pull/6767
> 
> What was confusing for my is that the actual release of rc.3 is 5 days ago. I assumed it was released from master on that same day but apparently it was released 7 days before. Not sure what happens in those 7 days.

**Comment by mattjohnsonpint** [comment]
Indeed, after updating to today's GA release, this issue appears resolved.  Thanks!
