### ISSUE TITLE
Border clipping issue

### ISSUE THREAD

**Issue by IeuanWalker** [dotnet/maui#7211]
### Description

Adding a border around a VerticalStackLayout has a weird clipping issue. 

![image](https://user-images.githubusercontent.com/6544051/168489328-8339ac24-0946-4858-9aed-c02f086973c1.png)

### Steps to Reproduce

```xaml
<Border Grid.Row="0"
        Padding="0"
        BackgroundColor="#E5F7FF"
        Stroke="Transparent"
        StrokeThickness="5">
    <Border.StrokeShape>
        <RoundRectangle CornerRadius="200" />
    </Border.StrokeShape>
    <Border.Triggers>
        <DataTrigger Binding="{Binding IsSelected}"
                        TargetType="Border"
                        Value="true">
            <Setter Property="BackgroundColor" Value="#ECEAFF" />
            <Setter Property="Stroke" Value="#4E16FF" />
        </DataTrigger>
    </Border.Triggers>
    <VerticalStackLayout Padding="10">
        <Label HorizontalTextAlignment="Center"
                Text="{Binding DayOfTheWeekLetter}"
                TextColor="#00A2EE" />
        <Label HorizontalTextAlignment="Center"
                Text="{Binding Date, StringFormat='{0:dd}'}"
                TextColor="Black" />
    </VerticalStackLayout>
</Border>
```

### Version with bug

Release Candidate 3 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

android 11

**Comment by IeuanWalker** [comment]
possibly related to #7103

**Comment by jsuarezruiz** [comment]
I have been testing on the current main branch. I can't reproduce the issue. This issue must have been fixed by https://github.com/dotnet/maui/pull/6851

![Screenshot_1652691455](https://user-images.githubusercontent.com/6755973/168556912-d193ec44-b75b-4d95-b903-663fc4d3f9df.png)

**Comment by IeuanWalker** [comment]
@jsuarezruiz here is a repo project - 
[Repo.zip](https://github.com/dotnet/maui/files/8698862/Repo.zip)

I've got the latest VS Pre installed

**Comment by IeuanWalker** [comment]
@jsuarezruiz sorry just saw that that PR hasnt been released yet, thanks, will wait for the fix

**Comment by jsuarezruiz** [comment]
I am going to close this issue as it seems to be fixed  for the next Release. If the problem persists or you find something related, let me know so I can reopen the issue!

**Comment by HausBJB** [comment]
Hello the problem is still there

Version GA (32.0301)

https://github.com/dotnet/maui/issues/6804

**Comment by HausBJB** [comment]
Ok because this change
https://github.com/dotnet/maui/pull/6851/commits/f0cf10d285e09cb8900ac8e1bfbd1cd18b49df74

flew out again with this one

https://github.com/dotnet/maui/commit/b8727a40b18bd12a8707af146e19b8be87e86086
